### ISSUE TITLE
cirq.Rz(-pi) shows up as Z^-1 in circuit diagrams

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1080]
Repro:
```
import cirq
import numpy as np

a = cirq.NamedQubit('a')

circuit = cirq.Circuit.from_ops(
    cirq.Rz(-np.pi).on(a)
)

print(circuit)
```

Output:
```
a: ───Z^-1───
```

Expected behavior:
Maybe it should just be Z?

The reason for this behavior is that the period of a gate returned by Rz is explicitly set to 4 instead of 2.

**Comment by Strilanc** [comment]
I will fix this after https://github.com/quantumlib/Cirq/pull/1055 , which allows EigenGate to compute its own period (and in particular the unshifted period)

**Comment by viathor** [comment]
The solution to this issue would have been simpler if we could examine group properties of the gates more easily. I suggested one way to achieve this is on #1099.

In the specific instance of this issue, the suggestion on #1099 would help by making the internal representation of Z and Z^-1 identical! (because -1 = 1 mod 2).
