### ISSUE TITLE
Define __getitem__ for TrialResult

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1288]
Should obtain measurements.

**Comment by dabacon** [comment]
I think this still makes sense and the return type should be `ndarray`

**Comment by kevinsung** [comment]
Well, we could also make `trial_result[key]` return `trial_result.data[key]` instead of `trial_result.measurements[key]`. The return type would then be a Pandas Series. Now that I think of it, this ambiguity makes a case for not implementing this.

**Comment by dstrain115** [comment]
Didn't you just implement this @dabacon ?  I think we can close this now.

**Comment by dabacon** [comment]
No I made EngineJob results indexable.  So still open.

**Comment by Strilanc** [comment]
In the pandas dataframe results, `dataframe[key]` returns the column by key (all samples for a given measurement by key). If we want to be consistent with that, we would match it.

**Comment by mpharrigan** [comment]
The fact that it isn't obvious to us what this should return might suggest that it's best to not implement it and have users type what they want after a dot

**Comment by dstrain115** [comment]
We have decided not to do this, as there is too much ambiguity and it is not that hard to type ".data" or ".measurements" after the TrialResult to disambiguate and clarify which one you want.

As an aside, I have also decided not to rollback getitem for EngineJob since that iterates over TrialResults and is not ambiguous.  Closing this issue.
