### ISSUE TITLE
Produce LaTeX using qpic

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1290]
I think the diagrams are nicer: https://github.com/qpic/qpic

**Comment by bryano** [comment]
How important is it to produce nice-looking non-text diagrams using latex, rather than say directly rendering things using, e.g., pysvg? I'm strongly in favor of abandoning qcircuit, which is based on xypic, whose syntax is very difficult to parse without diving deeply into the reference guide. My concern is that qpic, based on tikz, won't be much better in that regard.

**Comment by Strilanc** [comment]
I'm very much in favor of dropping qcircuit in favor of something better. Not only do qpics diagrams look better, the code looks easier to edit (because you don't have to do column-oriented editing).

I do think it's important for us to output latex, because I think it will often be the case that users will want to customize the output slightly (e.g. add a highlight box). I would also like to have the option to output svg images. Having multiple modalities will also prevent us from over-specializing the diagramming code (...hopefully).

**Comment by dabacon** [comment]
It would be useful for someone to do a deep dive into qpic and list the advantages and disadvantages versus qcircuit.  

One significant advantage to qpic is that it has an open source repo https://github.com/qpic/qpic so if we run into shortcomings we could contribute upstream.

**Comment by dabacon** [comment]
Tracking this in #1492
