### ISSUE TITLE
Quantum circuits in example doc strings not rendering correctly

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1297]
See: https://cirq.readthedocs.io/en/latest/examples.html

**Comment by vtomole** [comment]
@Strilanc https://imgur.com/a/D16T6IE

**Comment by Strilanc** [comment]
That's actually not nearly as bad as I was picturing. On my windows machine the lines often just don't line up at all, because the fonts aren't fixed width when it comes to unicode.

I think it's not devastating for the lines to be italicized like this. Not ideal, but the intention is still getting across. Worth fixing, but not urgent.

**Comment by dabacon** [comment]
We need an updated example of this. @vtomole do you see somewhere else in the documentation where this is a problem?

**Comment by dstrain115** [comment]
I removed the direct quotation of these examples in the docs and instead link to the source code.  I don't think this issue is relevant anymore.  Please re-open if you find other instances of this in the docs.
