### ISSUE TITLE
Add "user best practices" to documentation

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1373]

**Comment by c-poole** [comment]
This is where a "preferred" default method for achieving basic tasks like putting operations into circuits can be specified as discussed at the Hands-On Workshop.

**Comment by balopat** [comment]
A bit more details here would help. We do have a best practices section on the Google side - but there is no such thing in general. @Strilanc @dstrain115 @dabacon @c-poole - can you bullet point the ideas that were mentioned on the workshop?

**Comment by dstrain115** [comment]
Yes.  This was a long-standing request where we could tell people the "right" way to do things, especially where there are multiple ways to do things.

The one thing I remember is that people should use cirq.Foo rather than package names.  So, prefer cirq.X  instead cirq.ops.X.

This would kind of be like a cirq style guide.  

There's probably a fair amount of work to gather these practices together.

**Comment by dstrain115** [comment]
Adding a few more people on this old issue, since it recently came up that users may not know that Gates should be immutable.  We should add this to the documentation hack-a-thon for Cirq 1.0
