### ISSUE TITLE
googlebot can't detect CLA from co-authored commits even if all the authors have signed the CLA

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1536]
Example: https://github.com/quantumlib/Cirq/pull/1528

**Comment by Strilanc** [comment]
Unfortunately, this is out of our control and also it is working as intended. In particular, just because someone signed the CLA doesn't mean they intended for the specific code that someone else is submitting to be handed over. It's not possible for a script to make that determination well, and so it requires manual override.
