### ISSUE TITLE
For QASM of decomposed circuits add comment

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1622]
I noticed that if I export CCZ into qasm, I get the h, ccx, h operations with no leading comment saying that they correspond to a CCZ. I'm pretty sure this used to happen.

**Comment by dabacon** [comment]
Confirmed this is still true. 
```
a, b, c = cirq.LineQubit.range(3)
circuit = cirq.Circuit(cirq.CCZ(a, b, c))
print(cirq.qasm(circuit))
```
returns
```
// Generated from Cirq v0.7.0

OPENQASM 2.0;
include "qelib1.inc";


// Qubits: [0, 1, 2]
qreg q[3];


h q[2];
ccx q[0],q[1],q[2];
h q[2];
```

**Comment by daxfohl** [comment]
I can take this as a first issue.

The hacky way to do this would be to hard-code this comment string into [`CCZ._qasm_`](https://github.com/quantumlib/Cirq/blob/0ff2894e053e4ce3bb1b54e9b9de1cc4345d10b3/cirq/ops/three_qubit_gates.py#L138). 

The better way would be to have ccz with exponent=1 decompose into [h, ccx, h]. The problem is that ccx decomposes into ccz, so it gives an infinite loop. Would we want to muck around with the decomposition orders just for this?

Another option would be to augment [`should_annotate`](https://github.com/quantumlib/Cirq/blob/0ff2894e053e4ce3bb1b54e9b9de1cc4345d10b3/cirq/circuits/qasm_output.py#L311) with an extra condition that checks if the generated qasm is multi-line. This change would cause some additional gates that are not currently commented to be so. [`h_with_parameter`](https://github.com/quantumlib/Cirq/blob/0ff2894e053e4ce3bb1b54e9b9de1cc4345d10b3/cirq/circuits/qasm_output_test.py#L185) would be `// Gate: H**0.25`, and [multi-qubit identities](https://github.com/quantumlib/Cirq/blob/0ff2894e053e4ce3bb1b54e9b9de1cc4345d10b3/cirq/circuits/qasm_output_test.py#L460) would be annotated e.g. `// Gate: I(3)`.

**Comment by daxfohl** [comment]
Opened a PR for the issue. That PR goes with the third option: augment the `should_annotate` to annotate any multiline output.

At first I was thinking the second option would be preferred, but I no longer think so. What an operation decomposes to, and how an operation is best represented in qasm are different things. (for instance, ccx decomposes, but can be represented directly in qasm).

I originally thought the third option was a hack, but now it seems to me to be the most natural: if the qasm expands beyond one line, *whether because of decomposition or because of a custom qasm definition*, then annotate it.
