### ISSUE TITLE
Should we started enforcing no overlap between measurement keys and parameter names?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1686]
This comes up when analyzing data afterwards. It's ambiguous whether you're talking about the measurement result "a" or the parameter "a".

**Comment by dabacon** [comment]
I guess this could be a problem but the way you access these makes it pretty clear they are different.  I'm inclined to close this since I'm not aware of anyone making this mistake, and if they do it's mostly because we have moved too far in the direction of returning objects that don't allow you to understand what you are accessing (probably also a vote against the idea that we should eliminate `TrialResult`.

**Comment by dabacon** [comment]
Closing unless we think there are places where this is causing confusion.  As was mentioned you can get confused between the rows and columns of data frames, but I don't think not allowing them to overlap is a good idea (it's a strange restriction that just adds complexity while only supporting a few people who might possibly get slightly confused).
