### ISSUE TITLE
TrailsResult's data frame will fail for more than 64 qubits due to integer conversion.  

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1807]
(Still exposed as a list by legacy methods though)

**Comment by dabacon** [comment]
I'm not sure flattening to int is the right call for all users though it appears that this was done.

At the very least this needs to document the endian-ness of this conversion, which is not done in `TrialResult`.  

Also this will fail at 64 qubits because pandas data type is int64 in our current code.

**Comment by dabacon** [comment]
Oh this does work, my bad.  Closing this issue.

We do need to document this in sampler.
