### ISSUE TITLE
Move api protobuf definitions from cirq.api.google to cirq.google.api

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#1873]
It's rather confusing to have both of these packages, so I propose we restructure. In particular, I would suggest that we move the protobuf definitions for v1 and v2 into `cirq.google.api.v1.protos` and `cirq.google.api.v2.protos`, respectively. We can reesport the `*_pb2` packages in the `__init__.py` for the `cirq.google.api.vN` packages, so that both protos and various helper functions can be used with a single import. One question would be whether we also want to change the package declarations in the proto files, since they would not match the python package location anymore. Thoughts?

**Comment by dabacon** [comment]
I agree it would be nice to move these.  Need to be careful in doing this with downstream dependencies.

**Comment by dstrain115** [comment]
Oh dear.  This is going to be painful.

I propose copying the protos from cirq.api.google to cirq.google.api so that there are two copies of all the protos temporarily.

Once everyone has switched over to using the new package name, then we can get rid of the old one.

This will cause some annoyance, since we will need to update two copies of protos for a little while, but it hopefully won't break anything.

What do people think?

**Comment by dstrain115** [comment]
The list of things that need to change packages that I know about are:

- cirq
- cirq_internal
- pyle
- google3

I think that most other projects should be using the public interfaces of cirq rather than using the api directly.
