### ISSUE TITLE
Handedness between ISwapPowGate and FSim is different.

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1882]
The ISwapPowGate and FSim gate rotate in different directions on the |01>, |10> subspace.  This feels a bit odd to me.

**Comment by viathor** [comment]
This morning I meant to change signs of the angles in fSim only to notice that @maffoo has already done this in #1726. It seems that his PR missed ISwapPowGate. I'll send out a fix soon.

**Comment by Strilanc** [comment]
https://quantumcomputing.stackexchange.com/questions/2594/what-is-the-matrix-of-the-iswap-gate

![image](https://user-images.githubusercontent.com/79941/61984533-a98e5a00-afb9-11e9-846d-ec69ff7b3c75.png)

**Comment by Strilanc** [comment]
Changing these kinds of conventions is a silent breaking change on our users. The iswap gate has been around for several versions now; we can't just change what it means.

Personally I don't mind so much if iswap is at fsim(-90deg) instead of fsim(+90deg).

If we want to change this convention, we first need to deprecate iswap for one version then delete it for one version then re-introduce it with the new convention.

**Comment by viathor** [comment]
OK.
