### ISSUE TITLE
Bug in Pauli multiplication

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1883]
The code
```
import numpy as np
import cirq

q = cirq.NamedQubit('a')
print(cirq.Z(q)**0.5 * cirq.X(q) * cirq.Z(q)**-0.5)
```
incorrectly yields
```
-X(a)
```
(the correct behavior, if we want to allow such expressions, is to yield `Y(a)`). Indeed, the code will yield `-X(a)` no matter what the Z exponent is:
```
import numpy as np
import cirq

q = cirq.NamedQubit('a')
theta = np.random.randn()
print(cirq.Z(q)**theta * cirq.X(q) * cirq.Z(q)**-theta)
```
always yields
```
-X(a)
```
The exponent is being ignored. The issue has to do with ```type(cirq.Z(q)**theta)``` being `cirq.ops.pauli_string.SingleQubitPauliStringGateOperation`, when maybe it shouldn't.

**Comment by dabacon** [comment]
Oh I didn't even notice this when I wrote that :(

**Comment by kevinsung** [comment]
The bug seems to be in line 108 of `pauli_string.py`:
```
                f, p = self[c].phased_pauli_product(other[c])
```
since `phased_pauli_product` does not take exponents into account. This leads to the question of whether we should allow PauliStrings to be initialized with exponentiated Paulis, since this leads to the related buggy behavior
```
import cirq

a = cirq.NamedQubit("a")

S = cirq.PauliString({a: cirq.Z**0.5})
X = cirq.PauliString({a: cirq.X})

print(S * X * S)
```
returning
```
-X(a)
```

**Comment by viathor** [comment]
The first issue above is caused by the fact that raising a `cirq.Pauli` (such as `cirq.X`) to a power (fractional or not) returns another instance of `cirq.Pauli`. In turn, `cirq.Pauli.on()` produces a `cirq.SingleQubitPauliStringGateOperation`. The latter pretends that multiplication is supported, but in fact implements an algorithm for Pauli strings only.

The fix is to ensure that raising `cirq.Pauli` returns an appropriate ?PowGate (for ?=X, Y, Z). This will raise an exception which is appropriate given that the underlying algorithm doesn't support non-Pauli gates.

The second issue where `cirq.PauliString` accepts a dictionary with non-Pauli values is a straightforward case of argument validation.

Will send a fix.
