### ISSUE TITLE
BUG: downcasting from complex in `apply_unitary`

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2041]
The following code to multiply PauliY by the identity incorrectly casts the matrix representation of PauliY into the type of the input state (float):
```
import cirq
import numpy as np
from cirq import protocols

y0 = cirq.PauliString({cirq.LineQubit(0): cirq.Y})
state = 0.5 * np.eye(2)
args = protocols.ApplyUnitaryArgs(target_tensor=state,
                                  available_buffer=np.zeros_like(state),
                                  axes=(0,))
result = protocols.apply_unitary(y0, args)
```
gives
```
>>> print(result)
[[0. 0.] 
[0. 0.]]
```
numpy correctly throws a warning about this casting, but this should really throw an error.

**Comment by dabacon** [comment]
This feels like a case where the code should use the larger type.

**Comment by MichaelBroughton** [comment]
Brought up again: Should just promote types as needed to complex.

**Comment by vtomole** [comment]
Taking this.

**Comment by vtomole** [comment]
Casting the types of `target_tensor` and `available_buffer` causes `_incorporate_result_into_target` to fail with the error:

```python
    if not (
        np.may_share_memory(args.target_tensor, sub_args.target_tensor)
        and np.may_share_memory(args.available_buffer, sub_args.available_buffer)
    ):
        raise ValueError(
            'sub_args.target_tensor and subargs.available_buffer must be views of '
            'args.target_tensor and args.available_buffer respectively.'
        )
```
I don't know how to get around this so the solution i can think of right now is requiring that the types of `target_tensor: np.ndarray` and 
`available_buffer: np.ndarray` be complex and fail otherwise.  

Anyway, I will bring this up at the sync.
