### ISSUE TITLE
Get measurement name from circuit in aqt_sample

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2195]
https://github.com/quantumlib/Cirq/blob/dd0934d833e1659951d6f9283c7f38355ba4d64e/cirq/aqt/aqt_sampler.py#L159

**Comment by dabacon** [comment]
Currently the measurement is hard coded to `m` and ignores a key that might be supplied in the circuit.

This is related to #2199 because AQT always assumes terminal measurements.  

Let's use #2199 to track as they are very related (likely AQT currently ignores measurements because always assumes terminal measurements).
