### ISSUE TITLE
invalid moment after routing

### ISSUE THREAD

**Issue by tbcdebug** [quantumlib/Cirq#2298]
I tried `router` in `cirq.contrib.routing` and it generated one moment with `CZ((6, 5), (5, 5))` and `CZ((6, 6), (7, 6))` in it. I thought there would be a problem because `(6, 5)` and `(6, 6)` are adjacent. I ran `validate_moment` on this moment and it agrees with me.

Well, I don't know what leads to this problem yet. Just to give you guys a heads-up. Also, I don't know if you have the target of making every moment after routing to be executable, but this seems to be a sensible target.

**Comment by bryano** [comment]
This is the intended behavior, as Sycamore doesn't have the cross-talk constraints that Bristlecone does.

If you want to run a circuit produced by the routing code on an `XmonDevice`, just run an optimization pass that moves simultaneous and adjacent 2-qubit gates into separate moments. This will be suboptimal, but because the routing code is targeted at Sycamore, there aren't plans to optimize the routing code to address this.

@Strilanc @mpharrigan Does this seem reasonable?

**Comment by mpharrigan** [comment]
That's right
