### ISSUE TITLE
test_single_qubit_op_to_framed_phase_form_output_on_example_case fails for me

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2324]
If I change 
```
    assert cirq.allclose_up_to_global_phase(u, cirq.unitary(cirq.X**0.5))
```
to
```python
    cirq.testing.assert_allclose_up_to_global_phase(u, cirq.unitary(cirq.X**0.5), atol=1e-8)
```

I get

```
E       Mismatch: 50%
E       Max absolute difference: 1.41421356
E       Max relative difference: 2.
E        x: array([[ 7.071068e-01+0.j      ,  2.018520e-16+0.707107j],
E              [-7.826198e-17+0.707107j,  7.071068e-01+0.j      ]])
E        y: array([[7.071068e-01+5.551115e-17j, 5.551115e-17-7.071068e-01j],
E              [5.551115e-17-7.071068e-01j, 7.071068e-01+5.551115e-17j]])
```

**Comment by Strilanc** [comment]
That's really strange. I was initially confused why you said "for me" in the title, but the changed line does pass on my machine.

Please reduce the test case as much as possible and try to figure out where the failure is happening. Specifically:

- Instead of producing the matrices from decomposition code, hard-code them.
- Simplify the matrices as much as possible (e.g. replacing small constants with zero) while preserving the disagreement between the two methods.
- Consider inlining the contents of `assert_allclose_up_to_global_phase` and `allclose_up_to_global_phase` and diagnose where the actual difference is coming from.

**Comment by mpharrigan** [comment]
I should clarify that the test fails whether I change the line or not. I changed it to get more diagnostic information.

I don't have a ton of time to debug this right now. Was wondering if this test fails for anyone else

**Comment by dabacon** [comment]
#2468 notes that this fails sometimes due to a faulty numpy install (which causes the test to fail on windows).  Going to close this in favor of that issue.

FWIW did not fail on my machine.
