### ISSUE TITLE
ParallelGateOperation for multi-qubit gates

### ISSUE THREAD

**Issue by smitsanghavi** [quantumlib/Cirq#2399]
Right now we limit `ParallelGateOperation` to single qubit Gates. Any issues to expanding it to multi-qubit gates? We can accept list of lists or validate that len(qubits)%len(gate.num_qubits)==0

**Comment by c-poole** [comment]
I don't think there would be an issue in expanding it other than needing to have a clearly documented convention for how the class will parse the qubit input and feed that into the gates for validation. The `NeutralAtomDevice` class may need some modification since `ParallelGateOperation` was created explicitly for the validation methods of that class and the single-qubit gate assumption is probably used implicitly in that code. Unless another `Device` class comes around that has similar constraints to `NeutralAtomDevice` but also needs them for multi-qubit gates (something I would be shocked by), I don't think this change would grant any significant utility.

**Comment by smitsanghavi** [comment]
Closing this since there isn't a use case for it
