### ISSUE TITLE
Switch from cirq-dev pypi package to cirq-unstable pypi package

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2431]
I think this is less confusing in important ways. Opinions?

@mpharrigan 
@dabacon 
@maffoo 
@cduck

**Comment by maffoo** [comment]
@Strilanc, can you describe the confusion you're hoping to prevent? I'm not tied to the name `cirq-dev`, just want to make sure I understand the thinking here and that we pick a different name that avoids the problems you see.

Another thing that I'd like to at least explore before we do this is whether it's possible to prevent pip from installing both cirq and cirq-whatever in the same virtualenv, since currently this is possible and leads to weird failures (see #2347). For people who now have cirq-dev installed, the same issue will come up if we switch to cirq-unstable, so if there's a way to fix this that would ease the transition.

**Comment by Strilanc** [comment]
> can you describe the confusion you're hoping to prevent?

We have the package variant cirq[dev-env], which installs a developer environment.
We have the alternate package cirq-dev, which installs the latest version of cirq from master.

They both use the word "dev" in a packaging context as a suffix to cirq, but it means drastically different things in each case.

**Comment by Strilanc** [comment]
> Another thing that I'd like to at least explore before we do this is whether it's possible to prevent pip from installing both cirq and cirq-whatever in the same virtualenv, since currently this is possible and leads to weird failures

The same thing happens with `tensorflow` and `tf-nightly`

```
mkvirtualenv breakage --python=/usr/bin/python3
pip install tf-nightly
python -c "import tensorflow"  # works
pip install tensorflow
pip uninstall tensorflow
python -c "import tensorflow"  # blows up
pip install tf-nightly
python -c "import tensorflow"  # blows up
```
