### ISSUE TITLE
cirq.mixture should work on unitary objects

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2439]
In fact, why not work on _any_ object? If it doesn't explicitly define a mixture, then just return the mixture composed of the object itself.

Actually, there might be reasons not to do that ...

**Comment by c-poole** [comment]
Based on @Strilanc 's previous presentation on how he would like these protocols to work, yes. We've also discussed renaming mixture so that it unambiguously only refers to mixtures of unitaries. I plan to implement this renaming as part of #1722. If we want to support mixtures of other concepts then each concept should have its own mixture protocol. Otherwise, any code that uses an ambiguous mixture protocol will have to go do unnecessary type-checking to ensure that it received a mixture of an object type it was expecting.

**Comment by Strilanc** [comment]
> Actually, there might be reasons not to do that ...

We specifically want mixture to refer to a mixture of unitaries, so this would be akin to asserting the object was unitary.

But yes, cirq.mixture should have a result if cirq.unitary does.

**Comment by 95-martin-orion** [comment]
This was fixed by #3026:

> mixture's behavior now matches what mixture_channel used to do (i.e. unitary objects have implicit mixtures)
