### ISSUE TITLE
gate.exponent  = new_exponent causes AttributeError: can't set attribute.

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2482]
I want to modify exponent of given gates to substitute old sympy.Symbol to new one. But it is not allowed because the gate.exponent as no setter. Is it intended design or may I add it?

**Comment by jaeyoo** [comment]
Hmm. I found out _with_exponent() but it is private. So I decided using the full type(a.gate)(exponent=sympy.Symbol('new')), but am afraid of _global_phase. Does cirq.decompose() guarantee that the generated gates have no _global_phase?

**Comment by cduck** [comment]
Closing because gates (and most objects in Cirq other than Circuit) are intended to be immutable.

If your goal is to substitute one symbol for another, you should use `cirq.resolve_parameters` to create a new gate.  This will work in general, even if the exponent is an expression involving that symbol.  `cirq.resolve_parameters` also works on `Operation` and `Circuit`.

```
>>> a = cirq.X(cirq.NamedQubit('q0')) ** sympy.Symbol('old')
>>> b = cirq.resolve_parameters(a, {'old': sympy.Symbol('new')})
>>> print(a)
X**old(q0)
>>> print(b)
X**new(q0)
```

**Comment by jaeyoo** [comment]
Thanks. I checked it works perfectly :)
