### ISSUE TITLE
Major goal: gate pattern matching

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2536]
- We have many different ways of specifying the same gate. An X gate could an instance of `PauliString`, of `XPowGate`, of `PhasedXPowGate`, of (in the future) `PhasedXZPowGate`, of `MatrixGate`, you get the idea. It would be nice if I could just say `cirq.match(might_be_x, cirq.X)` in order to recognize X gates, and `cirq.match(might_be_x, cirq.XPowGate)` to identify X rotations.

- I always accidentally write `if isinstance(op, GateType)` instead of `if isinstance(op.gate, GateType)` and then lose ten minutes figuring out what's wrong. It would be nice if this was not a possible mistake to make, e.g. `if cirq.match(op, cirq.IdentityGate)` worked and also `if cirq.match(gate, cirq.IdentityGate)` worked.

- Currently, in order to identify an identity operation from an `Any` you have to say `if isinstance(obj, cirq.Operation) and isinstance(obj.gate, cirq.IdentityGate)`. It would be nice if this had no `and` in it, e.g. `if cirq.match(obj, cirq.IdentityGate):`.

- I often want matching to be *approximate*. For example, `PhasedXPowGate(exponent=0.2, phase_exponent=1e-10)` should match into `XPowGate` when tolerance is larger than 1e-10.

**Comment by dstrain115** [comment]
One other use case is for the matching system to handle wrapped classes.  For instance, TaggedOperation wraps an underlying operation, but it is really the same "type" except with some extra tag information added onto it.  One can imagine other uses similar to this with wrapper classes.

**Comment by dabacon** [comment]
The "this gate is really this gate" pattern is probably good, but one thing about it is that is really really hard to discover.  This might make the case that it should be a protocol.  Combined with #2939 which suggest adding protocols to docstrings automatically this could lead to better discoverability.

**Comment by balopat** [comment]
Xref: Organize gate relationships #3242

**Comment by daxfohl** [comment]
Is this still seen as useful? It seems like probably a big effort, so do we think it would give reasonable ROI? If so I may want to start looking into it.

**Comment by balopat** [comment]
Absolutely. You'll have to talk to @tanujkhattar about this though, as he is introducing the concept of gate sets and reorganizing compilers, both of which will benefit / touch on / depend on this feature. Above all, here we'll need an agreed design - the longest part of this effort will be to figure out something we can all agree on.

**Comment by tanujkhattar** [comment]
### Description
`cirq.match(to_match, match_against)`
- `to_match` can be an _instance_ of 
  - `Gate` class
  -  Different operation classes with an underlying `gate` instance, eg: `GateOperation`, `TaggedOperation`, `ControlledOperation`, `ParallelGateOperation`. 
- `match_against` can be 
  - instance of a Gate Type (eg: `cirq.X`)
  - a Gate type (eg: `cirq.XPowGate`, `cirq.ControlledGate` etc.)
  
### Low Hanging Fruits (2 & 3)       
I propose we implement the first version of the `cirq.match` and replace all `isinstance`  checks with `cirq.match`. 
- Proliferation of `isinstance(op.gate, GateOperation)` to identify operations with gates is annoying and leads to bugs (see #3556, #4287, #4152 etc.). 
- `cirq.match()` can be easily implemented to check the different types of `to_match` and `match_against` and use the underlying `to_match.gate` for matching, in case of an operation. This will also solve the originally proposed 2nd and 3rd points in the description. 
- For cases when `match_against` has a unitary (i.e. gate instances), `cirq.match` can directly compare the unitaries of `to_match` and `match_against` for an approximate matching.
 
### Open Questions for discussion
- Directly using `to_ match.gate` for matching against `match_against` has a potential risk that some operations which have an underlying `gate` would not behave well / as expected in the surrounding context. Eg:
```python
def decompose_y_into_phased_x_z(op):
    if op.gate == cirq.Y:
        # we expect cirq.unitary(op) == cirq.unitary(cirq.Y), which is not the case here. 
        return cirq.single_qubit_matrix_to_phased_x_z(cirq.unitary(op))
decompose_y_into_phased_x_z(cirq.Y(q[0])) # Works as expected
decompose_y_into_phased_x_z(cirq.ParallelGateOperation(cirq.Y, cirq.LineQubit.range(5))) # Fails with an error
```
 - How to handle controlled gates? ControlledGates have two dimensions - `sub_gate` as well as `num_controls`. What if I want to check whether the given operation is a controlled X rotation with any number of controls? Can we use `cirq.match` for it? Is it a common use case?  eg: `decompose_multi_controlled_x` could take an operation and use `cirq.match(op, is_controlled_x_with_any_controls)` to check whether it can be decomposed or not. 

### Matching across types - high level thoughts(1 & 4) 
- I imagine that matching gates across types is as hard as converting `to_match` to an instance of `match_against`. Also, in many situations (eg: gate compilation) checking whether the gate is same across types will be followed by actually converting the gate to the required type. 
- Hence, 1 and 4 from the original proposal would likely be tackled via a compilation framework that can take a gate `to_match` and compile it to an instance of `match_against` if the compilation is possible / the gates are the same. 
- Since this is direct compilation, we could probably use an analytical solver to check for solutions by comparing unitary of `to_match` with the parameterized matrix representation of `match_against` where the later is a gate type?

**Comment by dstrain115** [comment]
@tanujkhattar Do we think this is done with GateFamily?

**Comment by tanujkhattar** [comment]
Yes, implementing equality across types for (potentially parameterized) gates is a hard problem. The preferred way to do this for specific use cases now is to use `cirq.GateFamily` (eg: see `cirq_google.FSimGateFamily`).

I'll mark this as closed now.
