### ISSUE TITLE
_BGate defined as complex conjugate of B gate

### ISSUE THREAD

**Issue by gecrooks** [quantumlib/Cirq#2624]
The B gate class in two_qubit_to_fsim.py appears to have been defined as the complex conjugate of the B gate as defined in the original reference (unless I'm making a sign error somewhere). It should be `XX(a, b)**-0.5, YY(a, b)**-0.25`,

https://github.com/quantumlib/Cirq/blob/2b88d34dc2c4dc5dc1c59d21810114112286c225/cirq/optimizers/two_qubit_to_fsim.py#L137

https://arxiv.org/abs/quant-ph/0312193

In a sense this doesn't really matter, since _BGate is only used internally to the module, and B and its conjugate are related by 1-qubit gates. But it might trip someone up down the line.

**Comment by balopat** [comment]
I think you're right, thank you for pointing it out!!
The `XX` gate is defined as <img src="https://render.githubusercontent.com/render/math?math=e%5E%7B-i%20%5Cpi%20%2F2%20%5Csigma_x%5E%7B(1)%7D%20%5Csigma_x%5E%7B(2)%7D%7D"> and implemented as such in our `XPowGate`. And `YY` is similar. I suspect that for the 2qubit decomposition work to FSim it still worked because of some symmetry. However just simply changing the decomposition to the other direction, it breaks all the tests. 

@viathor can you confirm our understanding here?

**Comment by viathor** [comment]
@balopat @gecrooks I agree that cirq's _BGate is the complex conjugate of B gate defined in the paper.

I think the decomposition works because the inverse B gate is locally equivalent to the B gate (e.g. conjugate by ZI), though I think some angles on the single-qubit gates may need adjustment.

We should fix this.

@gecrooks Thank you for catching this! Would you like to have a go at the fix?
