### ISSUE TITLE
Have Circuit inherit from collections.MutableSequence

### ISSUE THREAD

**Issue by MichalKononenko** [quantumlib/Cirq#2676]
Considering it already implements all the methods in [collections.abc.MutableSequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableSequence) anyway, why not have Circuit inherit from it?

**Comment by dabacon** [comment]
This was discussed at Cirq Cync.  

Arguments in favor:

1.  Allows one to check for if it is a mutable sequence using `isinstance`
2. Allows type annotation of collections.abc.MutableSequence for methods that use Circuit and some other class as possible arguments.

Arguments against:

1. Could box the class in a bit if we are thinking about Circuit containing anything beyond moments or other moment types
2. We believe the python methods that use this will already work, they just look for methods
3. There could be confusion with explicitly supporting this in that it implies that `reverse` should work, which it does, but the semantics of `reverse` could easily be confused with `cirq.inverse`.

The decision was made not to implement this due to the cons, but if we find a lot of use cases where we are having to single out type checking or type annotations then we will reopen.
