### ISSUE TITLE
Slicing histogram output

### ISSUE THREAD

**Issue by obriente** [quantumlib/Cirq#2679]
When histogram is called without a fold_func specified, the results can be interpreted as a sparse array, and it feels like it might be useful to be able to slice it (as one way of calculating marginals, for instance). However, this isn't implemented in the native collections.Counter class (as the key values are not necessarily integers).

Would it make sense to add this functionality to the output? (Sorry if this has been thought of and dismissed before.)

**Comment by balopat** [comment]
Thank you for opening @obriente! This sounds like a nice idea - I would love to hear more use cases to justify an implementation.

**Comment by obriente** [comment]
So as a simplest example:

import cirq
circuit = cirq.Circuit([cirq.H(cirq.GridQubit(0,0)), cirq.CNOT(cirq.GridQubit(0,0), cirq.GridQubit(0,1)),
                        cirq.measure(cirq.GridQubit(0,0), cirq.GridQubit(0,1), key='m')])
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=1000)
hist = result.histogram(key='m')
p0 = sum(hist[::2]) # Ideally, would return the number of measurements where GridQubit(0,1) returned 0
p1 = sum(hist[1::2]) # Ideally, would return the number of measurements where GridQubit(0,1) returned 1

**Comment by dabacon** [comment]
The number of keys in the counter can vary depending on whether the measurement was seen or not.  So in the example given if number of repetitions is 1, for example there will only be one element.  So I guess what is desired is to be able to slice according to the binary strings, not indices.

But then is the desired behavior to return a list with counts including 0 in the slice?  That would cause some issues in terms of efficiency since most histograms would have a lot of 0s.  

I'm wondering if the use case described here, where you want to get the marginals is what this should really be.  Something like subclassing Counter and then you can ask
`hist.marginal([0])` which returns the marginal with only the 0th qubit.

**Comment by dstrain115** [comment]
Decision from cirq cync:  For more complicated slicing and processing, the user could use the underlying numpy array of the measurements (instead of calling the histogram).  numpy has much more syntactic sugar for handling these sorts of operations.

**Comment by 95-martin-orion** [comment]
@obriente, have you found a workaround for this? Doug's comment describes the Cirq team's recommendation on this.
