### ISSUE TITLE
Cannot use pow() for user defined gates

### ISSUE THREAD

**Issue by knsmith** [quantumlib/Cirq#2702]
Hi,

When you try to create new gates using cirq.SingleQubitGate (in my particular case, dimension=3), pow() is not supported to create inverse operations. 

        class Qutrit_Chrest(cirq.SingleQubitGate):
                def _qid_shape_(self):
                        return(3,)
                def _unitary_(self):
                        return (1/np.sqrt(3))*np.array([[1, 1, 1],
                                [1, np.exp(2*np.pi*(0+1j)/3), np.exp(4*np.pi*(0+1j)/3)],
                                [1, np.exp(4*np.pi*(0+1j)/3), np.exp(2*np.pi*(0+1j)/3)]])
                def _circuit_diagram_info_(self,args):
                        return '[C_3]'
    
        q = cirq.LineQid.range(3, dimension=3)
        c = cirq.Circuit() 
        test_gate = Qutrit_Chrest()
        c.append(test_gate.on(q[0])**-1)

**Comment by c-poole** [comment]
I believe the only types of gates `pow()` works with out of the box are `EigenGates`. If you modify your gate class to inherit from `EigenGate`, `pow()` should start to work. The reason for this behavior is that raising a matrix to a general (non-integer) power isn't unique and although integer powers are unique, they are not special cased. `EigenGate` lets you specify the behavior of each Eigenspace of your operator so that raising the Gate/Operation to any real power is well defined.

**Comment by knsmith** [comment]
Thanks for the response! I'll try this out.
