### ISSUE TITLE
Document in cirq.apply_unitary's docstring that it can operate on qudit subspaces

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2862]
If you have a state tensor defined over qutrits, and you call `cirq.apply_unitary` targeting this state tensor but give it a qubit gate, apply_unitary will operate on the 01 subspace. This isn't currently documented but it should be mentioned in the docstring.

**Comment by aditya-giri** [comment]
@Strilanc I'd like to pick this up if that's okay - sounds like an easy first issue to get started with.

**Comment by aditya-giri** [comment]
Just to clarify with an example, since I'm new here - this means that if you have a qutrit (say, with states 0, 1, 2, and currently in the superposition `01 + 12`) - and you call `apply_unitary` but with a qubit gate instead of a qutrit gate, the unitary will only act on the 01 component and not on the `12`. Is my understanding correct?

**Comment by vtomole** [comment]
@aditya-giri  That's right.

**Comment by aditya-giri** [comment]
@vtomole does this also generalize to k-qubit gates applied to n-qubit systems (k<n)?

**Comment by daxfohl** [comment]
@Strilanc @vtomole instead of this would it make sense to add an optional argument to ApplyUnitaryArgs to specify the subspaces to operate on?
