### ISSUE TITLE
Define new state type that encompasses STATE_VECTOR_LIKE plus density matrices and use it in fidelity function

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2904]

**Comment by dabacon** [comment]
STATE_VECTOR_LIKE exists.  We likely need an equivalent for density matrices (should be different, though, right?)

This has not been added to fidelity in measures.py

**Comment by kevinsung** [comment]
In general, there is no way to distinguish between a density matrix and the state tensor of a pair of qudits (a type which is encompassed by STATE_VECTOR_LIKE). For example, consider the matrices
```
A = [[1, 0]
     [0, 0]]
B = [[0.5, 0.5]
     [0.5, 0.5]]
```
Both are valid density matrices for a single qubit, but they are also valid state tensors for two qubits. In the first case, their fidelity is 0.5, while in the latter, their fidelity is 0.25. Therefore, if we want functions like `cirq.fidelity` to accept both kinds of inputs, they will need additional information in order to distinguish these two cases when the inputs are two-dimensional arrays with the same shape. I can think of two solutions:
1. Force the user to specify the qid shape in this situation. I don't like this solution because I expect that the vast majority of the time, the user will be using density matrices, not state tensors.
2. Default to assuming density matrices, with a flag that can be set to change it to state tensors. Unfortunately the flag would have a complicated name like `two_dimensional_arrays_are_state_tensors` or something like that.

**Comment by balopat** [comment]
Discussed on Cirq Cynq: 

A final idea we came to as a conclusion to explore further: type system + a central utility function to interpret numpy arrays (by default as a density matrix).

**Comment by viathor** [comment]
More details on discussion: Kevin's example shows that in some contexts numpy array is insufficient to describe a quantum state. In such contexts, the additional information must be specified somehow. Below are a few possible approaches we discussed:

### Types

Very extensible in the sense that if in the future we find out we want to attach more information to states, the types would offer a natural place to do it. Also, type signatures would help document the code. However, users are burdened by having to wrap their states, so this is considered a "high friction" approach. 

### Keyword arguments

Continue to use numpy arrays, but in a few places where ambiguity exists use keyword arguments, e.g.:

```python
fidelity(state_vector1=np.array(...), density_matrix2=np.array(...))
fidelity(density_matrix1=np.array(...), density_matrix2=np.array(...))
```

### Function names

Put the extra information in function names instead:

```python
fidelity_state_vector_vs_density_matrix(np.array(...), np.array(...))
fidelity_density_matrix_vs_density_matrix(np.array(...), np.array(...))
```

Proliferates functions and pollutes namespace making autocomplete annoying.

### Shape argument

Have functions in which ambiguity arises accept an additional parameter:

```python
fidelity(np.array([[0.5, 0.5], [0.5, 0.5]]), np.array([[1, 0], [0, 0]]), qid_shape=(2,))
```

### Inference

Use types, but mostly internally and implement inference so that wherever a state is expected users can pass in either a numpy array or even a python list (for low friction) or cirq's special type for representing quantum states (for resolving ambiguity in cases where inference fails), e.g.:

```python
# cirq infers that both of these arrays describe single-qubit states
fidelity(np.array([0, 1]), np.array([1, 1])/np.sqrt(2))
# user tells cirq explicitly that the first is a single-qubit state, cirq infers the second
fidelity(density_matrix([[0.5, 0.5], [0.5, 0.5]]), [[1, 0], [0, 0]]) 

```

**Comment by viathor** [comment]
I like using types to solve problems and specify APIs, but I accept the "high friction" argument. Function names solution leads to proliferation of functions and pollution of cirq's namespace which would make autocomplete annoying (scrolling/searching through more names).

I think the real contenders are kwargs, shape and inference. Among these I think inference is the best because the other two make it harder to pass states between functions (you need to pass qid_shape or the right kwargs along).

**Comment by balopat** [comment]
@viathor thank you so much for capturing the details of the discussion - awesome notes. 

+1 for "inference" as well  
* I like to code against types (but I'm biased as I come from a statically typed background)
* explicit language makes the code more readable (I find `fidelity(density_matrix([[0.5, 0.5], [0.5, 0.5]]), [[1, 0], [0, 0]])` more readable than `fidelity(np.array([[0.5, 0.5], [0.5, 0.5]]), np.array([[1, 0], [0, 0]]), qid_shape=(2,))`
* well documented inference rules will reduce the overhead for users to learn the "type language" for the most frequently used paths (e.g. density matrices in the fidelity function's case)

**Comment by kevinsung** [comment]
I also like inference. If I understand correctly, this is how it would work:
- We create a QuantumState class that stores a numpy array and a qid shape.
- In the example `fidelity(density_matrix([[0.5, 0.5], [0.5, 0.5]]), [[1, 0], [0, 0]])`, the function `density_matrix` returns a QuantumState.

There is still the question of how the function `density_matrix` should infer the qid shape of its input. For example, a 4x4 density matrix could have qid shape either (2, 2) or (4,). For an nxn matrix, if n is a power of 2 then we should probably assume qubits. If n is not, then I'm not sure what we should do. Perhaps use the prime factorization?

**Comment by kevinsung** [comment]
For JSON serialization of the QuantumState data type it would be nice to have https://github.com/quantumlib/Cirq/issues/2742.
