### ISSUE TITLE
Change default serializable gate set in Engine from XMON

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2957]
1. This isn't documented in doc strings
2. Should this be upgraded to something more modern?
3. I assume lots of uses are having to specify this for every call, is this something that we should have an Engine level default for?  I think we have steered away from that pattern.

**Comment by maffoo** [comment]
Internally, we have code where we default the gateset to `None`. When a circuit is submitted and no gateset is specified, we try each gateset that the engine says it supports in turn until we find one that can serialize the given circuit and then use that. In practice, the first gateset that the engine claims to support should be the full "fsim" gateset, which can basically serialize any allowed circuit, so there's little overhead. This could possibly be made cleaner if there were a way to ask a gateset whether it can serialize a given circuit instead of just attempting to serialize and capturing any exceptions.
