### ISSUE TITLE
Remove need to specify Gateset for Engine calls

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2988]
It should be possible for a processor to know if it will support the given gates and the user not to have to specify the gate set.  This might mean that it needs to query the device spec before hand.  We could cache this (for sampler interfaces this could be done at construction time of the sampler).  Branched off from #2819

**Comment by 95-martin-orion** [comment]
@tanujkhattar is this complete? I remember Transformers removing some gateset-passing, but maybe not all of it.

**Comment by maffoo** [comment]
We made gateset optional for most engine calls in https://github.com/quantumlib/Cirq/pull/4983. As a follow-up, we plan to deprecate and eventually remove the `gate_set` args (https://github.com/quantumlib/Cirq/issues/4995) but since that's being tracked separately I think we can probably close this.

**Comment by dstrain115** [comment]
Closing this, as the direct issue (requiring gate set on calls) is complete and the remaining work is captured in other issues.
