### ISSUE TITLE
Methods for partial trace and separable part of state vector should work for qudits

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3003]
These methods should take an optional shape and use this.  Default would be to assume qubits.

**Comment by tonybruguier** [comment]
@dabacon 
Is this still needed? And if so, what is the function? Is it this one?
https://sourcegraph.com/github.com/quantumlib/Cirq/-/blob/cirq-core/cirq/linalg/transformations.py?L296

**Comment by daxfohl** [comment]
@tonybruguier It looks like `partial_trace` you linked to has worked for qudits since the original commit. I assume @dabacon means `partial_trace_of_state_vector_as_mixture`, which calls `sub_state_vector`, which has the following line.

https://github.com/quantumlib/Cirq/blob/d967317cdb0f954e14907f69aaae70fd1f76ff6f/cirq-core/cirq/linalg/transformations.py#L461

There is a test `test_partial_trace_of_state_vector_as_mixture_invalid_input` that highlights these.

**Comment by daxfohl** [comment]
Note there's a function `factor_state_vector` in the same file that seems to do roughly the same thing (and may work for qudits). I wrote that function, but none of the linalg experts signed off before it was merged (and in fact I'm nervous now that it's incorrect, as I'm definitely *not* a linalg expert and kind of made it up). It's used in simulation to factor the state vector after measurement.

**Comment by daxfohl** [comment]
After some thorough testing, I found a minor bug in `factor_state_vector`'s validation block, where it needs to account for a possible global phase shift. Fix is in #5076.

Everything else there seems to work the same as `sub_state_vector` (if the phase randomization is removed from the latter), except it also works on qudits (and is about 10x faster, and seems slightly more precise).

So using that should take care of qudits when the states are separable, but `partial_trace_of_state_vector_as_mixture` also has logic for non-separable states, so that needs to be adapted for qudits for non-separable states in order to close this issue.

(Note, I'm not planning to work on this, just relaying information).
