### ISSUE TITLE
Proper deprecation of `qubit` and `_qubits` on device

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3080]
There is hacky code in `cirq.Device` that falls back to these method for `qubit_set`, apparently according to the comment to preserve backward compatibility.  These other methods should be properly deprecated and removed instead.

**Comment by balopat** [comment]
If someone picks it up - this is the part in question:

https://github.com/quantumlib/Cirq/blob/72c2a9ff52bc947c022168593c0bf91bddb2fb6a/cirq/devices/device.py#L37-L44

And the test that ensures this behavior is in device_test.py / test_qubit_set. 

For proper deprecation, we can't use the `@deprecated` annotation as we don't have access to these attributes or methods, but we should try to imitate it: we should keep the test but also add tests for deprecation messaging that is consistent with the other deprecation messages (see cirq.ops.fourier_transform.QFT for example). We should aim to remove these by v0.10. 

Good first issue for someone!

**Comment by unaiic** [comment]
Would all the block of code be deprecated (apparently dropping backward compatibility) or only `qubits` and `_qubits`?

**Comment by balopat** [comment]
Since last Aug I learned a bit more about how we deprecate things. 
This is how I would do this: 

1. create a new generic `def deprecation_warning(deprecation: str, deadline:str, fix: str)` in `cirq._compat`. We should make sure that this method uses the `_warn_or_error` method in `_compat` and that it validates the `deadline` argument like the other deprecators. 
2. I would call this method inside this block: 
```
if hasattr(self, name): 
   _compat.deprecation_warning(f"{type(self)} class implements {name} method, which is deprecated", deadline="v0.12", fix="Implement qubit_set instead") 
    ...
```
3. I would add a test in `device_test.py` that tests the warning emitted with `cirq.testing.assert_deprecated` from a `Device` subclass implementing `qubits` and another implementing `_qubits`. 
4. After releasing v0.12, we can remove the whole block and just keep `qubit_set` an abstract method without implementation

Another design note: 

We have deprecation helpers for functions, parameter, module attributes and modules.
 This falls under the category of deprecating "private" functions that are used by protocols and/or abstract classes. We don't have a good design here yet, hence my recommendation is to write the generic `deprecation_warning` method. But maybe we could think a little bit more around something like 

```
method = _compat.find_deprecated_method_implementation(implementor=self, method_name='qubits', deadline='v0.12', fix='implement qubit_set_instead') 
if method is not None: 
   if callable(method): 
       val = method() 
   else: 
       val = method 
   return frozenset(val)
```

But I'm not convinced yet that this abstraction is very useful - so I would just go with the generic `deprecation_warning` method outlined above for now.

**Comment by MichaelBroughton** [comment]
This is going to be superceded by moving qubits information into devicemetadata. Think we are good to close here.
