### ISSUE TITLE
Run batch interface

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3135]
Collecting some thoughts on the new `run_batch` in hopes of cleaning up its interface.

First, information about the program batch structure is very hard to recover from the `EngineJob` or `EngineProgram`.  Losing this information means that downstream consumers need to be fed this separately to sort out the results.

Second here are some ideas to improve the interface on `EngineJob`:

* `batched_results` which return `List[List[TrialResult]]`
* `data` which returns pandas `DataFrame` for sweeps (columns for parameters).  Because different programs can have different parameters, this might have multiple columns with irregularly filled values for batch jobs but would be very useful for sweeps.
* `batched_data` which return `List[DataFrame]`.

**Comment by maffoo** [comment]
Thanks for starting this, @dabacon. I agree that we need a more structured result format for batches. I think if running one circuit gives `List[TrialResult]` then running a batch should give `List[List[TrialResult]]`. Currently, `TrialResult` knows how to convert itself to a dataframe, but it would be nice if we had a way to get a dataframe representing an entire sweep so having a way to get a `DataFrame` instead of `List[TrialResult]` for a sweep on one program makes sense; analogously there should be a way to get `List[DataFrame]` from a batch instead of `List[List[TrialResult]]`. I'm less sure if it makes sense to get a single `DataFrame` for a batch, since as you say the columns may not line up. I suppose we could support this if the sweeps params and measurement keys are "compatible".

**Comment by dstrain115** [comment]
Added batched_results in #3303
