### ISSUE TITLE
Colab link for notebooks

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3182]
https://colab.research.google.com/github/quantumlib/Cirq 

Brings up the notebooks in the project. It is kind of cool, but it requires a Google account to run them.
What do we think about adding it in the README.rst as a link to tutorials? 
(I also asked the same question in OpenFermion https://github.com/quantumlib/OpenFermion/issues/628 and we could do something similar in ReCirq as well @mpharrigan).

**Comment by balopat** [comment]
Good first issue!!! Whoever wants to work on it - should look at how OpenFermion implemented this to make it similar. I don't think we need binder link though.

**Comment by mpharrigan** [comment]
I'm sort of baffled by the interface that pops up. It's just listing all the notebooks in the repo? How does it order them? Happy to see all of my notebooks pop up first but they should likely be filed way further down after some more introductory tutorials :) :)

**Comment by mpharrigan** [comment]
When I try to run one, it gives a warning that it wasn't authored by google and may be malicious. It also doesn't work, since cirq isn't installed in the runtime

**Comment by balopat** [comment]
> When I try to run one, it gives a warning that it wasn't authored by google and may be malicious. It also doesn't work, since cirq isn't installed in the runtime

I see the warning is less of an issue, we should look into it if there is an easy way to get rid of that. 
The runtime installation is a great point - we should add 

```
import sys
if `google.colab' in sys.modules: 
  !pip install openfermion --quiet
```

to our notebooks alongside with this change.

**Comment by exAClior** [comment]
Being able to use Colab to run tutorials solves a lot of trouble for beginners! Don't have to worry about installing everything or creating a virtual environment or too much of your processing power been consumed by running cirq and your computer becomes laggy. 
But a heads up though, I tried to do this for tutorials from the blue team. Qiskit was huge and each time I want to run the notebook, I have to install everything. That took ages! Sort of defeats the purpose of having an experience of click and run which we have here. Just looking a bit into the future, we might want to find an elegant way to "host" the Cirq runtime on the google drive instead of doing runtime installation every time as Cirq grows larger.
Another problem is that we might run into dependency issues in the future. I remember trying to install qiskit on colab and there's dependency conflicts with colab's default installed packages in terms of versions. I could not find a way around that in the past.

**Comment by unaiic** [comment]
I could work on this. @balopat Should changes regarding runtime installation be included here as well? Also, if they were included, would it affect to every single notebook?

**Comment by balopat** [comment]
Thanks @unaiic for jumping on this! I think this should be closed, with the new site up and being integrated with Colab nicely, I think this is less important. I'm going to close this as @rmlarose suggested.
