### ISSUE TITLE
Compiling: Organize Gate Relationships

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3242]
**Problem:** There are currently 40 different gates in Cirq.  Many of these gates are related to each other.  A common pattern here is that a gate exists which is a subset of a more generalized gate.  This is particularly confusing when one attempts to use isinstance on gates.  In addition many gates implement the decompose protocol, and so there is some hidden relationship between these gates when they are decomposed.  This feature would be to define what is allowed for the relationship between gates and how decompose should be defaulted and documented.  A further question to be resolved in this feature is whether some of this organization should be delegated to gate set concepts.

**Rough requirements:**

- Catalog current gate relationships
- Define allowed relationships between gates and implement
- Decide how decompose should be used for Cirq gates.  For example should decompose not be implemented for the base Cirq gates and only allowed for composite gates that do not define their own action?

**Comment by smitsanghavi** [comment]
This sounds pretty nice to have. What are the expected benefits of establishing these relationships?

1. A more general `isinstance` implementation that understands these relationships might simplify some code (Some examples would be great here)
2. Easier Gateset validation/conversion once we have that feature

**Comment by balopat** [comment]
TODO(@balopat): scope this before we jump in figure out what exactly we want to do before Cirq 1.0

**Comment by tanujkhattar** [comment]
[Colab](https://colab.research.google.com/drive/1apQpYG5bY_qnuVsIJXLl48gxvUdE9JLz#scrollTo=Zvvf3AJkX2yF) to visualise current Cirq Gate Relationships.

**Comment by daxfohl** [comment]
Adding takeaways from conversation with @tanujkhattar for posterity:
* Avoid pushing into protocols if possible -- that hard-codes everything and we want to keep flexibility / exensibility.
* Try to find a MVP use case: is there a set of 5 or fewer gates that we could start with and would add value somewhere?
* Idea: Rule sets that can be mixed and matched, and a rules engine that processes them.

**Comment by tanujkhattar** [comment]
I've been thinking about this roadmap item and so far, I think the existing problems are:
1) We don't have a way to visualize the decompose relationships among gates and hence it can be confusing for users 
2) We implicitly decompose all gates to a particular 1/2 qubit gateset and users can start depending on this implicit gateset, which is something we discourage but don't currently enforce. 
3) The inheritance relationships among gates and operations are convoluted (/very flexible :)) and hence code pieces using isinstance checks run into bugs all the time. 

However, there are also many benefits of having decompose and flexible inheritance relationships among gates. I'm curious to find out what other problems arise in practice due to the complex gate relationships in Cirq.

**Comment by tanujkhattar** [comment]
RFC for organizing decompose relationships: https://tinyurl.com/cirq-organize-decompose-rfc

**Comment by tanujkhattar** [comment]
Decompose now decomposes to cirq's default gateset and all operations now have underlying gates (except only circuitops and cco's). 

The only feature addition left for this roadmap item is to add a convenience method `cirq.plot_decompose(op_tree)` to visualize the various decompose relationships and it's being tracked in a separate issue and not blocking the Cirq 1.0 release.

We can thus close this roadmap item and mark it as completed.
