### ISSUE TITLE
Support for AWS Braket

### ISSUE THREAD

**Issue by iirekm** [quantumlib/Cirq#3253]
It seems that Cirq supports only Google devices, but they seem to be closed for public access :-(

Do you plan support for publicly-available devices, eg [AWS Braket](https://aws.amazon.com/braket/hardware-providers/) ?

**Comment by vtomole** [comment]
We don't only support Google devices. We support [AQT,](https://github.com/quantumlib/Cirq/tree/master/cirq/aqt) and [IQM](https://github.com/quantumlib/Cirq/tree/master/cirq/aqt) devices too. You can compile Cirq circuits to QUIL and run them on Rigetti's devices and also compile them to QASM to run them on IBM's.

**Comment by balopat** [comment]
+1 to @vtomole's comments!

Cirq is an open source **framework** for quantum circuits that allows users to directly access quantum computing platforms that decided to partner with us. AQT, IQM and [Pasqal](https://pasqal.io/) as well are the current examples beyond Google's devices.
Where direct access is not implemented, there is an option for "import/export" between Cirq's langauge to the other quantum computing platform's circuit language: PyQuil, OpenQASM (IBM), quirk, qcircuit (latex) are examples. 

In comparison AWS Braket is a managed service by AWS that charges for accessing the quantum computing platforms. 
AWS Braket comes with an [SDK](https://github.com/aws/amazon-braket-sdk-python) for which a circuit "import/export" functionality could be implemented. However, for Cirq quantum annealers are not in scope - so that part is unlikely to be supported.
