### ISSUE TITLE
cirq.contrib.quimb fails with quimb 1.2.0

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#3263]
**Description of the issue**

Quimb fails with version 1.2.0.  We should either require 1.3 or (ideally) fix whatever was broken in 1.2

**How to reproduce the issue**
```
pip install quimb==1.2.0
pytest cirq/contrib/quimb/
```

<details>
test_tensor_expectation_value
...
 AttributeError: 'numpy.complex128' object has no attribute 'add_owner'
</details>

**Cirq version**
cirq from HEAD and quimb == 1.2.0

**Comment by mpharrigan** [comment]
It fails in `rank_simplify`. I think the fix is this line: https://github.com/jcmgray/quimb/commit/492201519157355b751d64af73e297a318f0adff#diff-382c633ca92381427ca0bc74c1ac3081R3361

One option is to comment out `state_vector.py:150` which calls `rank_simplify`. It's possible EITHER that (1) this will cause performance to deteriorate in a major way for gridlike circuits because lots of things can be fused ahead of any true contraction OR (2) `contract` already finds a path that does this so it's fine.

Instead of truly investigating this, I say we set the requirements to `>=1.3.0` and if someone is desperate to use `1.2.0` they can patch out that specific line. What do you think?

**Comment by dstrain115** [comment]
So, it looks like this doesn't quite work in our favorite environment, since it looks like the version number is not super well specified.  Maybe it got pulled from master or something:

This is the error:
"invalid literal for int() with base 10: '0+unknown'"

I think it is fine for it to assume unknown versions are not compatible, but it should not error out.
