### ISSUE TITLE
Support cirq.commutes(operation, moment)

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#3274]
It would be handy to be able to easily check if an operation commutes with everything in a moment. For example, it makes things like https://quantumcomputing.stackexchange.com/questions/13488/reordering-commuting-gates-in-cirq-to-reduce-circuit-depth easier to implement.

Currently, checking if a moment and an operation commute raises an exception saying the case hasn't been implemented.

Here's a simple implementation, which has the downside of having quadratic overhead when comparing two moments.

```
    def _commutes_(self, other: Any, *, atol: float) -> bool:
        for op in self.operations:
            op_result = protocols.commutes(op,
                                           other,
                                           atol=atol,
                                           default=NotImplemented)
            if not op_result or op_result is NotImplemented:
                return op_result
        return True
```

**Comment by balopat** [comment]
Thanks for filing this! It should be easy to avoid the quadratic overhead in the moment vs moment case by checking commutation only between operations that share at least one qubit.

**Comment by akushnarov** [comment]
Esteemed, 

I've started working on this issue. Cirq is pretty new for me and I would need some guidance here, could you please advise?

Especially my question was:
Where it is better to implement "commutes" functionality:
- In the "[commutes_protocol.py](https://github.com/quantumlib/Cirq/blob/master/cirq/protocols/commutes_protocol.py)" (by extending the list of strategies, see the [diff](https://github.com/quantumlib/Cirq/compare/master...akushnarov:master))
- OR in the Moment class ("[moment.py](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/moment.py)"), by implementing a method "_commutes_"?

Also I would need some support in writing tests, since I'm not that good at modelling what commutes and what doesn't. Anyone can guide me?

Thanks and I appreciate any help
Andriy

**Comment by akushnarov** [comment]
1. As discussed on the https://gitter.im/cirqdev/community, I'm going to implement the solution on the `Moment` class side.
2. As for the tests I will take into account the feedback (from the same channel):

> Regarding testing, I think it should be relatively easy to cook up some testcases, just experiment a bit with cirq.commutes(op1, op2) where op1, op2 are different operations on qubits (e.g. cirq.X(cirq.NamedQubit(“a”))). Now, for a Moment, you’ll have a list of these guys, so it should be straightforward to create testcases. A Moment commutes with a given operation if all of its operations commute with it. If an operation does not share qubits with another operation, they trivially commute.

**Comment by akushnarov** [comment]
Hey @balopat, could you please check the [proposed solution](https://github.com/quantumlib/Cirq/compare/master...akushnarov:issue3274?expand=1), if no comments I'll create a pull request

**Comment by balopat** [comment]
Hey @akushnarov, create the PR and we can continue from there, it's easier to comment on a PR!

**Comment by akushnarov** [comment]
@balopat here is the [PR](https://github.com/quantumlib/Cirq/pull/3519)

**Comment by akushnarov** [comment]
FYI I added an issue 3529 (as it was discussed separately).
