### ISSUE TITLE
Better formatting for cirq code

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#3292]
I find the autoformatting that we currently use in cirq to be less than ideal. There are three main issues:
- yapf formatting is often bad, particular with things like nested tuples but also due to mixing hanging versus 4-space indentation styles (here's an example of [mixed indentation](https://github.com/quantumlib/Cirq/blob/master/cirq/google/op_deserializer_test.py#L93))
- 80 character lines seem to be too short, particularly with heavy use of type annotations as we have in our code.
- The incremental formatting is line-based, so we have lots of old code that has never been formatted.

**Describe the solution you'd like**

- Switch formatter from yapf to [black](https://github.com/psf/black). Black's formatting algorithm is simpler and the resulting formatting is more predictable and regular than yapf's, IME.
- Increase the line length to something like 100 characters. I think this would cut down on a lot of unnecessary line breaking and improve readability of the code.
- Switch the incremental autoformatting to be file-based instead of line-based. As part of doing this, we would have a one-time change to format the entire code base, which would be a massive diff but entirely automated. There's also a bit of work to update PRs that are in-flight at the time of the big formatting change, but this too is manageable.

**Describe alternatives/workarounds you've considered**

- Could increase line length without switching from yapf to black.
- Could tweak various yapf knobs to possibly improve the formatting (I prefer black's approach of having fewer knobs in the first place so there's less to argue about, but YMMV).
- Could switch to file-based incremental formatting and pay the one-time cost of formatting all old code without switching to black.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by mpharrigan** [comment]
I absolutely hate the yapf formatter and it often makes my code less readable. I also think a line length of 100 strikes a better balance between screen real-estate and superfluous wrapping. 

I personally like the pycharm formatter. It leaves things alone that don't break any of the rules. While that means there isn't a "canonical" way to format things, it lets the code author use line breaks and indentation to indicate intent, e.g. when building a nested list of stuff. Of course, it's much more difficult to install and run the pycharm formatter than a command-line utility. 

File-based incremental sounds good. A massive formatting change scares me, but may be our best bet. Maybe we can use that as motivation to get the number of open PRs down :)

**Comment by balopat** [comment]
1. I'm totally open to the 100 cols change - sticking to 80 chars seems archaic / obsolete in 2020. We can start there with yapf as well. 
2. I'm going to need more convincing about black for now
   a.) maybe because I haven't seen it in action that much, it just seems like "another formatter". I'm going to start to play with it and maybe I'll get excited. If you have features that you are excited about would help too. But I'm yet to see the "killer feature" that makes the whole change-over worthwhile.
    b.) yapf allows for the Google style guide - which is simple and is aligned with the rest of the Google projects - this might be imperfect but avoids arguing - I'm worried that with black even though there is small amount of knobs we will open a can of worms of bike-shedding and multiple massive formatting changes as we evolve to the "perfect formatting". 
3. file-based formatting - if we do that I think we'll see significantly more "massive formatting changes". Why? As far as I understand, today as the style changes (which will inevitably occur even with black), those changes "propagate" with only touched lines. This results in minimal "massive formatting changes" and minimal formatting noise during PRs, however we have potentially inconsistent styling in the codebase (today `yapf --style=google --recursive --in-place .` results in 440 changed files). 

I am a little bit worried about having an noisy git history too - git annotations really help understanding previous decisions, and while black [offers a workaround using ignore-rev-files](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame) which should work with IDEs, it is not integrated with Github, and will add more dev setup for all of our contributors.

My first impressions with black: 

1. It's fast! It took 25 seconds on my Mac to format the repo. The same for yapf took 5.3minutes!
2. I like that it reformats string formatters, simplifies them when it can
2. Sometimes it changes strings with double quotes to single quotes sometimes it doesn't (maybe for multiline ones it leaves them as double quotes?)
3. it breaks on some of our files - someone will need to investigate if these are blockers / issues with black or easily fixable - however it worries me that the formatting tool breaks on working code. 
```
...
Oh no! 💥 💔 💥
673 files reformatted, 33 files left unchanged, 7 files failed to reformat.
```

Those 7 files are giving errors like this: 

```
error: cannot format /Users/balintp/dev/proj/Cirq/cirq/sim/density_matrix_simulator_test.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/lk/h2pmhk456999cwnrm162297400fv8w/T/blk_u_drp37v.log
```

**Comment by maffoo** [comment]
@mpharrigan and @balopat, thanks for your comments!

@balopat, It looks like the formatting errors you see are a regression in recent black (I suspect it's due to a recent change to how they handle trailing commas). If you `pip install black 19.10b0` it seems to work and should give you a better sense of what black formatting looks like.

Re your questions:
2a) Picking a formatter is of course subjective, so saying I like black's formatting better doesn't carry much weight. But I do think black's formatting is objectively more consistent and predictable due to a simpler formatting algorithm. The simplicity is also reflected in the >10x speedup in formatting that you observed vs yapf. The main "feature" I like is the lack of knobs so there's less to bikeshed about wrt formatting. I think this will pay back over time and IMO it would be worth a single large-scale change to regularize the formatting.

2b) I don't know of any material differences between the formatting that black produces and google style; are there differences that you are particularly concerned about? I think black is becoming the "standard" formatter for the broader python ecosystem (see its adoption by psf), which is probably more important to align with than google internal style.

3) It's true we will see a big formatting change when we first switch to black, but IME incremental upgrades to black produce manageably small deltas even when applied all at once across a large codebase. This again goes to the simplicity of the formatting algorithm. I've seen much bigger diffs with incremental updates to yapf since the formatting is "annealing"-based so small internal yapf changes can have large effects on the resulting format. I think a single large diff when we switch formatters is better than spreading the changes out over time, but I understand that people may weight this differently.

**Comment by balopat** [comment]
This is done now! Thank you @maffoo!
