### ISSUE TITLE
Discrepancy in __iadd__ vs. __add__

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3353]
**Description of the issue**
Adding gates to circuits behaves differently when using `circuit + gate` vs. `circuit += gate`.
It's not immediately clear which one of these behaves "correctly". Related issue: #3246.

**How to reproduce the issue**
```
    a = cirq.NamedQubit('alice')
    b = cirq.NamedQubit('bob')
    c = cirq.Circuit(
        cirq.Moment(cirq.H(a), cirq.X(b)),
        cirq.Moment(cirq.X(a)),
    )
    g = cirq.H(b)

    cg = cirq.Circuit(c)
    cg += g

    # FAILS
    assert cg == c + g
```

<details>
cg (result of +=):

```
alice: ───H───X───

bob: ─────X───H───
```

c + g:
```
alice: ───H───X───────

bob: ─────X───────H───
```
</details>

**Cirq version**
0.9.0.dev

**Comment by maffoo** [comment]
It looks like `Circuit.__add__` first [wraps](https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/circuit.py#L269) non-circuits into a `Circuit` and then calls `__iadd__`, which in turn calls `append`. When appending a `Circuit` or `Moment` to another circuit, we preserve the moment structure, which is why `__add__` leaves the added Hadamard gate in its own moment but `__iadd__` moves it back into the available space. It seems to me we should avoid this wrapping and prefer the `__iadd__` behavior, but perhaps @Strilanc had a reason for doing it this way?

**Comment by balopat** [comment]
While one could argue that casting up to Circuit is the correct solution (making both operands the same type) as it is happening in `__add__`, however:
1. `__iadd__` then should do the same (e.g. in case of lists `[2,3,4] + [3]` and `a_list += [3]` work but `[2,3,4] + 3` and `a_list += 3` don't
2.  I think personally the `append` behavior is more intuitive. 

All in all +1 that we shouldn't wrap, but rather `append`. 

Deprecation note: probably this should be okay to change...but maybe it will surprise people, so we should add a note in the release notes about this behavior change.

**Comment by balopat** [comment]
Discussed at Cirq Cynq: append is the way forward for both without Circuit() wrapping.

**Comment by 95-martin-orion** [comment]
> Discussed at Cirq Cynq: append is the way forward for both without Circuit() wrapping.

Point of clarification: this means that we will keep the current `circuit += gate` behavior and change the `circuit + gate` behavior to match.
