### ISSUE TITLE
Read the docs has goofy copyright

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#3402]
**Description of the issue**
Copyright shows up on cirq tutorials on readthedocs.

**How to reproduce the issue**
Go to https://cirq.readthedocs.io/en/latest/docs/gates.html or other pages.  Top part says "Copyright 2020 The Cirq Developers" with apache license.

**Cirq version**
0.9.1.  It probably broke when we adjusted all the copyright notices.

**Comment by balopat** [comment]
This is the standard header that @lamberta put on every notebook as part of the devsite migration - including the buttons that I strip out during sphinx doc building as they looked even worse. 
It didn't bother me too much because we'll shut down RTD soon, and I'd expect less people to look at the latest link. 

I guess I can strip out the header cell as well fully from RTD publishing. I wonder how ReCirq got around this? @mpharrigan @lamberta?

**Comment by lamberta** [comment]
The license was a legal requirement for the notebook docs so we need it in the source notebook. But we remove it on the website because we already display the (same) license info in the footer.

For publishing to RTD, stripping it is fine with me as long as it remains in the source.

**Comment by mpharrigan** [comment]
I did some minor stripping here: https://github.com/quantumlib/ReCirq/pull/64/files#diff-1135f4acf7ec38e9ff5417b385142a20R162 in ReCirq. If you really wanted, you could probably munge out entire cells. I don't think it's a huge issue since we're moving off RTD and the new build system does strip the license info

**Comment by balopat** [comment]
@mpharrigan yeah, I'm removing the title, already in Cirq inspired by your stripping. I just don't see the ReCirq notebooks having these "@titleLicense" fields on the website (https://recirq.appspot.com/recirq/index.html) is that because you haven't published it since then?

**Comment by balopat** [comment]
Anyways, it is easy to strip it so I just raised a PR to avoid confusion while we still have the `latest` RTD site up
