### ISSUE TITLE
Equal circuits may have unequal measurement keys

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3452]
**Description of the issue**
Circuits which are equal do not necessarily have equal `all_measurement_keys` output. Encountered in #3445, where it prevents the use of `@lru_cache` to cache FrozenCircuit details.

**How to reproduce the issue**
Run the following python code (partial copy from `test_all_measurement_keys` in `cirq/circuits/circuit_test.py`):

```python
import cirq

a, b = cirq.LineQubit.range(2)
circuit_1 = cirq.Circuit(
    cirq.Moment([
        cirq.measure(a, key='x'),
        cirq.measure(b, key='y'),
    ]))
keys_1 = circuit_1.all_measurement_keys()

circuit_2 = cirq.Circuit(
    cirq.Moment([
        cirq.measure(b, key='y'),
        cirq.measure(a, key='x'),
    ]))
keys_2 = circuit_2.all_measurement_keys()

assert circuit_1 == circuit_2  # True
assert keys_1 == keys_2  # False: ('x', 'y') != ('y', 'x')
```

**Cirq version**
0.10.0.dev

**Comment by maffoo** [comment]
It seems to me there's no meaningful sense in which `all_measurement_keys` should be ordered. I would suggest we change it to be a set, or at least document that the order is not meaningful. This seems similar to the [`parameter_names`](https://github.com/quantumlib/Cirq/blob/master/cirq/protocols/resolve_parameters.py#L83) protocol where we return a set. I presume tuple was chosen in the `measurement_keys` protocol because it is immutable; for `parameter_names` we type the return value as `AbstractSet` which does not include mutating methods in the interface but gives us the flexibility to return either `set` or `frozenset` as desired.

**Comment by balopat** [comment]
The only reason I could guess why insertion order was preserved in the ordering measurement keys is to control the output ordering of `cirq.Result`...but I don't see any evidence of that from a cursory look. It is undeniably better to rely on sorting based on intrinsic properties of the measurement keys if needed at all - which the set semantics express much better. Thanks for reporting and the quick fix!
