### ISSUE TITLE
Zenodo citation author

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3490]
The authorship of "Quantum AI team and collaborations" for the zenodo citation link, I think, is not really correct.  1) Unlike the quantum computing effort at Google, not everyone on that team contributes (nor even the vast majority) to Cirq. and nit 2) It doesn't say Google, it just says "quantum AI team", which doesn't really inform anyone about the authors who does not work at Google.

I suggest that this should either list authors expressly, via those who have actually contributed to Cirq, or it should use "Cirq Developers" as is done in the copyright.

**Comment by balopat** [comment]
Thank you for opening this - I agree that this is not correct, I was just following the ReCirq pattern which could be also questioned but probably more correct than here. I like "Cirq Developers" as it is easy. The full authorlist is challenging given that not even all our contributors share their real names. Defining a cut-off at a commit count would be a reasonable idea, but that still doesn't help with the real name issue. 

cc @quantumlib/cirq-maintainers - what do you think?

**Comment by dstrain115** [comment]
@balopat Which citation is this?  Can you point me to the right place?

**Comment by maffoo** [comment]
+1 for "Cirq Developers". What's that saying about every problem being solvable by adding a level of indirection? If it is possible to add extra information when publishing to zenodo, we might add a link to the [contributors](https://github.com/quantumlib/Cirq/graphs/contributors) page on github. Even if we can't publish that to zenodo, we could consider adding that link to the readme where the zenodo citation is located, so people can go see for themselves who is included in "Cirq Developers".

**Comment by maffoo** [comment]
@dstrain115, it's in the readme: https://github.com/quantumlib/Cirq#how-to-cite-cirq

**Comment by dstrain115** [comment]
Oh, I agree, I don't think that's the correct way to cite cirq.  My suggestion is to change it to "Google Quantum AI and Cirq Developers" for now (our current official designation combined with the term we use in the copyright notice).  We may also want to run this by our internal (pubpy) publication committee as well. 

This is not the same as ReCirq, which is primarily Google experiments, so I don't think we should feel constrained to use the same thing as that one.  I also don't think listing specific authors is a good idea either, since we may not have consent of the author's, we may not know their real names, and the list will be changing over time.

Also open to other suggestions.

**Comment by balopat** [comment]
I like Cirq Developers + link to Contributors page from the notes field [in the metadata](https://developers.zenodo.org/?python#deposit-metadata). Great idea on asking for guidance from pubpy. Thank you!

**Comment by balopat** [comment]
This is confirmed now - the verdict is "Cirq Developers + link to Contributors page from the notes field in the metadata"- I just need to raise a PR and fix it :)
