### ISSUE TITLE
Showcase protocols based on annotation

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3512]
Instead of manually maintaining the list of notable protocols we could annotate them, so that they will be included in the main protocols docs. 

```
for o in dir(cirq.protocols):
    obj = eval(f"cirq.protocols.{o}")
    if callable(obj) and not isinstance(obj, type):
        docs = obj.__doc__
        if docs is not None:
            first_line = docs.split('\n')[0]
            print(f"|`cirq.{o}`| {first_line} |")
        else:
            raise ValueError(f"{o} has no public docs and it's a protocol function!")
```

_Originally posted by @balopat in https://github.com/quantumlib/Cirq/pull/3485#discussion_r526554704_

**Comment by dstrain115** [comment]
We have decided that this changes so infrequently that we do not need to handle this automatically.  In addition, the protocols notebook states that these protocols are a subset of the total protocols that are commonly used.

We probably should put cirq.protocols in back ticks so that it links correctly, but otherwise, we think this is fine for the foreseeable future.
