### ISSUE TITLE
Inconsistent canonicalization of FSim angles

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#3542]
**Description of the issue**

`FSimGate` and `PhasedFSimGate` disagree on whether or not theta and phi angles that are used by `__init__` and are exposed as properties are canonicalized (by projecting them into [-pi, +pi]) or not.

**How to reproduce the issue**

```
In [1]: import cirq, numpy as np

In [2]: for t in (-3/2, -1/2, 1/2, 3/2):
   ...:     theta = np.pi * t
   ...:     g = cirq.FSimGate(theta, 0)
   ...:     print(theta, g.theta)
   ...: 
-4.71238898038469 -4.71238898038469
-1.5707963267948966 -1.5707963267948966
1.5707963267948966 1.5707963267948966
4.71238898038469 4.71238898038469

In [3]: for t in (-3/2, -1/2, 1/2, 3/2):
   ...:     theta = np.pi * t
   ...:     g = cirq.PhasedFSimGate(theta, 0)
   ...:     print(theta, g.theta)
   ...: 
-4.71238898038469 1.5707963267948966
-1.5707963267948966 -1.5707963267948966
1.5707963267948966 1.5707963267948966
4.71238898038469 -1.5707963267948966
```

**Cirq version**
0.10.0.dev

**Comment by verult** [comment]
The behavior of canonicalizing on initialization is different from other gates:

* In `cirq.PhasedXZGate`, canonicalization is in the [equality check]((https://github.com/quantumlib/Cirq/blob/d967317cdb0f954e14907f69aaae70fd1f76ff6f/cirq-core/cirq/ops/phased_x_z_gate.py#L105) and [construction from matrix](https://github.com/quantumlib/Cirq/blob/d967317cdb0f954e14907f69aaae70fd1f76ff6f/cirq-core/cirq/ops/phased_x_z_gate.py#L120).

* `cirq.EigenGate` also only canonicalizes in the [equality check](https://github.com/quantumlib/Cirq/blob/d967317cdb0f954e14907f69aaae70fd1f76ff6f/cirq-core/cirq/ops/eigen_gate.py#L321).

Should we make this consistent across Cirq gates so as to not surprise users?

**Comment by tanujkhattar** [comment]
@verult Do you have an example of where this becomes an issue? Regarding consistency, I would consider things to be inconsistent if the same parameter (eg: exponent) is treated differently in similar gates (eg: X/Y/Z). 

So, for example, if `X ** 2.5` implicitly became `X ** 0.5` because we canonicalized the exponent during construction, but didn't do so for `Z ** 2.5`. 

`FSim` gate has different parameters (theta, phi) and till the time it's consistent with what happens in `PhasedFSimGate`, I don't see much issue here. Also, changing behavior of `EigenGate` will be a large breaking change, which I'd prefer to avoid unless we have a good reason to do so.

**Comment by verult** [comment]
Not a major issue for me. For context, I discovered this while implementing `PhasedXZGateFamily` using `FSimGateFamily` as an example, and a check like [this](https://github.com/quantumlib/Cirq/blob/fa473b44edfd0bd8d41a2c313a0894296ca0905e/cirq-google/cirq_google/ops/fsim_gate_family.py#L385) won't work for the `PhasedXZGate` because exponents aren't canonicalized on initialization. But we could easily fix this by instantiating a dummy `PhasedXZGate` with 0 angles and do a gate equality check.

> Regarding consistency, I would consider things to be inconsistent if the same parameter (eg: exponent) is treated differently in similar gates (eg: X/Y/Z).
Both exponents and FSimGate angles are derived from angles at the end of the day, and are canonicalized based on angles. So to me keeping their canonicalization process consistent makes sense to me, but I'm not a user so I don't have a strong preference :)

Agree that changing `EigenGate` would be big. If we do want to do this, changing `FSimGate` and `PhasedFSimGate` might be easier.

**Comment by 95-martin-orion** [comment]
Discussed at Cirq sync: an argument could be made for this as a cleanup item, but leading into 1.0 there isn't a strong enough motivation to justify directing time towards it.
