### ISSUE TITLE
Remove CliffordTableau

### ISSUE THREAD

**Issue by tonybruguier** [quantumlib/Cirq#3567]
**Is your feature request related to a use case or problem? Please describe.**
The CliffordTableau is still not being removed from the CliffordSimulator because direct_fidelity_estimation still relies on the availability of stabilizers from CliffordState. 

**Describe the solution you'd like**
We can move to use the tableau directly

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**
https://github.com/quantumlib/Cirq/pull/3564

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P1

**Comment by tonybruguier** [comment]
Happy to take this on if you want me to.

**Comment by smitsanghavi** [comment]
Thanks for creating the issue, Tony. I can take it up. 

By a quick glance at the `direct_fidelity_estimation` implementation (for Cliffords), it seems to just be iterating over the circuit and using `CliffordSimulator`'s`apply_unitary` on all the ops. After that it just needs the `stabilizers` from the final state to proceed. It seems easy to just switch to using `CliffordTableau` instead of `CliffordState` and `act_on` protocol instead of `apply_unitary`. It will also add the ability to handle any measurements the circuit might have. Let me know if that sounds good or if I'm missing some caveat.

**Comment by tonybruguier** [comment]
I sent you:
https://github.com/quantumlib/Cirq/pull/3571
