### ISSUE TITLE
Different versions of pytest for different checks

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3831]
`dev_tools/notebooks/requirements-notebook-tests.txt` has `pytest>=6.0.0` whereas `dev_tools/conf/pip-list-dev-tools.txt` has `pytest~=5.4.1`. We should make these consistent so I can set up a local environment to perform the various checks. 

Also, it's confusing that there are requirements files all over the place and it's confusing that it's named `pip-list-dev-tools.txt` instead of something like `dev-requirements.txt`. `pip-install-minimal-for-pytest` parses a requirement file (with many greps (but also sneaks in an extra requirement)). Maybe we can have one giant dev requirements file with machine-readable comments delineating which requirements are the minimal requirements for the various checks.

**Comment by mpharrigan** [comment]
The mypy check also greps the dev requirements for `mypy` which omits stubs for e.g. numpy, causing #3767 to not be picked up by the CI

**Comment by balopat** [comment]
+100 - it would be nice to consolidate all of these into a single place and jobs be able to "select" from them easily (any ideas around that? I don't like the grep based solution too much, it's error prone, string based...)
The pytest versions should be definitely the same, the notebook reqs was a mistake on my end.

**Comment by mpharrigan** [comment]
1. Roll our own simple syntax for mixing-and-matching requirements for different configurations. Maybe write requirements in a Python datastructure and have it "render" requirements.txt files
2. Check if a tool like the above exists in the community and is well-supported
3. A completely different approach: Have one loose `install_requires` spec in `setup.py` and have one large, fully-pinned CI requirements and use github actions caching to avoid the performance penalty of having all of them. This could fix problems like #3767 not showing up on the CI and would finally fully accomplish #3552

**Comment by maffoo** [comment]
One way to do this is that requirements files can include other requirements files, so you could have `pytest-minimal-requirements.txt` and then have the notebook requirements file include the line `-r pytest-minimal-requirements.txt` to include those. There are caveats, in particular last time I checked pip would break if any dependency got included more than once (even if the same version) so the include graph has to be a tree with no package appearing in more than one requirements file. But this might be enough for what we need. Also, I'd suggest that we not try to get too granular since I think that makes it hard to reason about what environment the different checks run in (and can lead to problems such as the missing stubs issue mentioned by @mpharrigan).

**Comment by mpharrigan** [comment]
is this fixed @balopat ?

**Comment by balopat** [comment]
Yes it is! :) Thank you!
