### ISSUE TITLE
Deprecate rx/ry/rz/ms factory functions

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#3929]
**Description of the issue**
The following free functions should be deprecated in favour of using the underlying gates directly. 
cirq.rx  --> cirq.Rx
cirq.ry --> cirq.Ry
cirq.rz --> cirq.Rz
cirq.ms --> cirq.MSGate

**Cirq version**
0.11.0.dev

**Comment by maffoo** [comment]
I got started on this and it turns out the `cirq.r*` rotation functions are used in a lot of places. The main difference from the `cirq.R*` gates is that the functions don't require a keyword arg, so that instead of `cirq.Rx(rads=pi)` you can do `cirq.rx(pi)`, which seems like a nice shorthand for some very common operations. Before we go to the trouble of fixing all the use cases, I just want to make sure we really want this (no comments here indicating this was ever discussed at a cirq sync).

@quantumlib/cirq-maintainers, thoughts?

**Comment by maffoo** [comment]
@MichaelBroughton, do you have a preference here?

**Comment by MichaelBroughton** [comment]
I think we should leave as is. I'm in favor of closing (it would be a lot of work to get this done pre 1.0).
