### ISSUE TITLE
Replace cirq.Symbol with sympy.Symbol / sympy formulas

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#393]
The docstring says
>A constant plus the runtime value of a parameter with a given key.

Is using the constant offset implemented yet? Shouldn't that be an attribute?

Also, I will want to use multiplication instead of addition. Can we also support a constant _times_ the runtime value? I'm happy to help with this.

**Comment by kevinsung** [comment]
I describe a use case here: https://github.com/quantumlib/OpenFermion-Cirq/issues/282

**Comment by Strilanc** [comment]
We've decided to go ahead and do this. We're looking for a volunteer to get this done, e.g.a  20%-er, because it's a reasonably independent reasonably large project. It involves going over the whole code base and doing little refactorings, and merging sympy's featureset with our needs. So there's a bunch of coding work but also a little bit of design work.

**Comment by vtomole** [comment]
I'm not familiar with Sympy. Could you please expand on what advantages and disadvantages "Allow Symbol to be a Sympy expression"  will have? Thanks!

**Comment by Strilanc** [comment]
The main advantage is that sympy supports algebra on symbols (i.e. you can make formulas), and it does a much better job of it than we ever would. Instead of being limited to just `X^t` as a parameterized gate, you could make a `X^(t^2 + 3 arcos(theta) - 1)` gate.

Now, in practice we won't be able to communicate those gates with arbitrary formulas to the service. Don't worry about that. It just has to work with the local simulator.

**Comment by dabacon** [comment]
Found a pretty bad place where this bites us pretty badly.  The way we define the Rx gate (which most people will use) we only allow the radians to be passed in and then we rescale it.  So you cannot use symbols with the Rx gate.

**Comment by Strilanc** [comment]
@dabacon We were *already* being bitten by that. Having the method just makes it more blatant. (This is why @babbush has been bringing it up; they prefer radians and so have been running into it.)

The change @vtomole is making will address this as a side effect, though it might be a few iterations before it starts to work.

**Comment by vtomole** [comment]
@Strilanc Don't close yet as that pull request didn't address not the whole repo. (paulistring).

**Comment by Strilanc** [comment]
It auto-closed because somewhere in the PR it said "Fixes bla".
