### ISSUE TITLE
Zip

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#4034]
**Is your feature request related to a use case or problem? Please describe.**

A very common pattern in building quantum circuits is to have a bunch of two qubit gates that you want to put into a circuit, and you do this by acting on qubits from two lists
```python
for q0, q1 in zip(qubits0, qubits1):
  cirq.CNOT.on(q0, q1)
```
In a similar way to having `on_each` we could, for two qubit gates, have `zip`:
```python
cirq.CNOT.zip(qubits0, qubits1)
```
I'm unsure if this could also be extended across multiple qubit gates (or even be another way to do `on_each`).

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by maffoo** [comment]
What if instead we were to extend `on_each` to all gates and allow it to accept a sequence of _tuples_ of `cirq.Qid` for gates that apply to multiple qubits? Then you could do
```python
cirq.CNOT.on_each(zip(qubits0, qubits1))
```
This is not quite as concise, but more general since you can construct the sequence in other ways in addition to using parallel lists.

One problem with this would be that the current implementation of on_each tries to be flexible by "flattening" nested iterables down to a single list of qubits (it seems likely that this was meant to support `cirq.X.on_each(q0, q1)` and `cirq.X.on_each([q0, q1])`, but the actual implementation supports any amount of nesting of sequences). It's possible this could be made to work by leaving the last level "unflattened" for multi-qubit gates. Probably would still not be able to support "variadic" gates like measure and wait since they could take one or more qubits.

**Comment by balopat** [comment]
Funnily @dabacon had a comment about the tuple version of `on_each` here a year ago: https://github.com/quantumlib/Cirq/issues/2164#issuecomment-624887247

I think generalizing `on_each` to `cirq.Gate` makes sense, and then we can deprecate `Single/Two/ThreeQubitGate` classes.

**Comment by balopat** [comment]
Discussed on Cirq Cynque: 
- on_each for 1-qubit gates will stay the same
- on_each for n-qubit gates will be strict - require Iterable of n-tuples 
- we'll deprecate `Single/Two/ThreeQubitGate`

**Comment by daxfohl** [comment]
Small suggested addendum to the above: copy `Single/Two/ThreeQubitGate` to `cirq.testing` when deprecating from `gate_features`, as unit tests become more cumbersome when you have to redefine these everywhere.

**Comment by daxfohl** [comment]
Deprecating Two/ThreeQubit gate here: #4207. (these can be done independently of the on_each migration; only SingleQubitGate deprecation must happen strictly after on_each migration).

I'll work on the on_each migration next.

**Comment by daxfohl** [comment]
Added `on_each` to `Gate` in #4236.

Note that deprecating `SingleQubitGate` will be more troublesome than the others, as things like `_CALIBRATION_IRRELEVANT_GATES` and `NOISE_MODEL_LIKE` depend on it.

**Comment by daxfohl** [comment]
For n-qubit gates which of the following do we want to allow (2-qubit examples below that would all represent the same thing):

A: varargs form `gate.on_each([q1, q2], [q3, q4])`
B: explicit form `gate.on_each([[q1, q2], [q3, q4]])`
C: flexible form `gate.on_each([[[q1, q2], [q3, q4]]])`, `gate.on_each([[q1, q2], [[[q3, q4]]]])`, etc.
D: flat varargs form: `gate.on_each(q1, q2, q3, q4)`

Is B is the primary one we were thinking? Do we want to support any of the others? Do we explicitly want *not* to support the rest of them?

**Comment by maffoo** [comment]
I played around with this a while ago but never made a PR, so I just put up my branch in #4262. The changes there support all the options that you listed (I worked on this before the cirq cynque discussion about more limited `on_each` support).

**Comment by daxfohl** [comment]
Yeah my initial attempt tried to be too general too. I updated #4236 to support option B only. There's lots of tests that show what is supported and what isn't. In particular `gate.on_each(zip(list1, list2))` is supported but `gate.on_each(*zip(list1, list2))` isn't.

**Comment by 95-martin-orion** [comment]
This is complete: `Gate.on_each(zip(qubits_0, qubits_1, ...))` provides the requested support and deprecated classes have been removed.
