### ISSUE TITLE
Cannot add identity to PauliSum

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#4087]
**Description of the issue**

Identities cannot be added to PauliSums. This might be related to `cirq.IdentityGate` not being a `cirq.Pauli`.

**How to reproduce the issue**

```
ps = cirq.PauliSum()
ps += cirq.I(cirq.LineQubit(0))

# Generates the error:
# TypeError: unsupported operand type(s) for +=: 'PauliSum' and 'GateOperation'
```

**Cirq version**
0.11.0.dev

**Comment by 95-martin-orion** [comment]
In lieu of a fix, users can wrap identity gates in `cirq.PauliString`s before mixing them into `PauliSum`s to avoid this issue.
```
psum = cirq.PauliSum()
pstr = cirq.PauliString(cirq.I(cirq.LineQubit(0)))
# does not fail
psum += pstr
```

**Comment by ybc1991** [comment]
Another shorter workaround is 
```
ps = cirq.PauliSum()
ps += 1*cirq.I(cirq.LineQubit(0))
```

but I was also wondering if `cirq.XPowerGate(exponent=0)` acts same as `IdentifyGate` or not. (Seems no except global phase difference).

**Comment by viathor** [comment]
The `PauliString` class maps sets of qubits to Pauli gates. This representation makes an implicit assumption that the operator corresponding to any given key-value pair in the dictionary acts as a scalar multiple of the identity on qubits which are not members of its key. This has a special case for scalars: scalar is an operator that acts as a scalar multiple of the identity on all qubits, hence the empty key.

This gives us another workaround for the issue:

```python
ps = cirq.PauliSum()
ps += 1
```

which actually works fine at the moment. I think that the above code snippet and

```python
ps = cirq.PauliSum()
ps += cirq.I(cirq.LineQubit(0))
```

should have the same effect once the issue is fixed.
