### ISSUE TITLE
Switch to ubuntu-latest in Github Actions

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4136]
**Description of the issue**

The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. We need to migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287.

**Comment by stubbi** [comment]
@balopat is there a reason you propose `ubuntu-latest` instead of `ubuntu-18.04`? I think specific version tags are generally preferable.

**Comment by balopat** [comment]
I just copy pasted the warning ;) I'm okay with 18.04!

**Comment by stubbi** [comment]
@balopat alright!

I noticed there [is even ubuntu-20.04 available](https://github.com/actions/virtual-environments#available-environments). Please, have a look at #4148 where I made the change. I had to [adapt the bazel install](https://gist.github.com/diegopacheco/10f4d7be75574e53e91c49f19bf2613f) which is working now. Also set the `2019` version tag for windows instead of `latest`.
