### ISSUE TITLE
Community examples

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4177]
It would be great to have a list somewhere (site, github markdowns) where we can point to interesting uses of Cirq - these can be demos, pet projects, etc. Opinions?

**Comment by tonybruguier** [comment]
I’ve been looking into quantum embeddings (https://arxiv.org/pdf/2008.08605.pdf) for machine learning (https://arxiv.org/pdf/2001.03622.pdf, https://arxiv.org/pdf/2101.11020.pdf). I also wrote a small demo (https://github.com/tonybruguier/sandbox/blob/master/quantum_embeddings.py) and I am not sure how to proceed (work on it more, send PR for an example, send PR for core Cirq, not submit anything, something else)
Do you have any advice on how to proceed?

**Comment by dstrain115** [comment]
Notes from cirq cync:  This would be a non-trivial effort of upkeep, and there is a tricky question of what we accept or deny and how it's promoted.

We are leaning against this proposal since it will be difficult to maintain and upkeep.  In addition, Tony's changes have found a different home (TFQ examples page) and other research might be better to host on ReCirq instead.  

For now, we will close this as not going to implement.  If Balint or any other want to make a pitch for this, they can join a future cirq cync to make a case for it.  We are open to revisit this, but, for now, will close it as not accepted.
