### ISSUE TITLE
Consolidate SQRT_ISWAP gate definitions

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#4223]
**Is your feature request related to a use case or problem? Please describe.**

Recently, #4213 added (will add) the SQRT_ISWAP=ISWAP**0.5 gate to the core set of gates.  Several places throughout Cirq define it and one place even defines it as [ISWAP**-0.5](https://github.com/quantumlib/Cirq/blob/2f8326c5f71006ff17c9353e30d35cd9e11aca2a/cirq-google/cirq_google/calibration/xeb_wrapper_test.py) (see https://github.com/quantumlib/Cirq/search?q=SQRT_ISWAP for the full list) which could lead to inconsistencies or bugs.

**Describe the solution you'd like**
These duplicate definitions `SQRT_ISWAP = ISWAP**0.5` should be removed and all uses of the gate should be updated to `ops.SQRT_ISWAP` or `cirq.SQRT_ISWAP` as appropriate.  https://github.com/quantumlib/Cirq/search?q=SQRT_ISWAP lists all places that need to be updated.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by ShrillShrestha** [comment]
Hi @cduck, I am a beginner learning to contribute to open source. I am not sure if I completely understand the issue, but I would like to try solving this issue. I might be able to work on it with some guidance.
Correct me if I am wrong, for example, [here](https://github.com/quantumlib/Cirq/blob/0311e1746acdb4519f334c421a90e15ff3035891/cirq-google/cirq_google/optimizers/convert_to_sqrt_iswap.py), are we trying to remove
https://github.com/quantumlib/Cirq/blob/0311e1746acdb4519f334c421a90e15ff3035891/cirq-google/cirq_google/optimizers/convert_to_sqrt_iswap.py#L21
and use `cirq.SQRT_ISWAP` instead of `SQRT_ISWAP` in every single occurrence of `SQRT_ISWAP`?

And, are we just considering the cases where we have `SQRT_ISWAP = ISWAP**0.5` or  `SQRT_ISWAP = ISWAP**-0.5`?

**Comment by cduck** [comment]
That's correct.  Within cirq-core, use `ops.SQRT_ISWAP` and use `cirq.SQRT_ISWAP` elsewhere (`cirq.ops` is used to avoid circular dependencies within cirq-core).  If the file uses `ISWAP**-0.5`, this is equivalent to `cirq.SQRT_ISWAP**-1` (i.e. x**-0.5 = (x**0.5)**-1).

**Comment by ShrillShrestha** [comment]
Thanks for the clarification. I will try to solve and issue a PR. I will let you know if I have any questions. :)

**Comment by maffoo** [comment]
I like the idea of consolidating these definitions. I'd suggest that we define both `SQRT_ISWAP = ISWAP ** 0.5` and `SQRT_ISWAP_INV = ISWAP ** -0.5`.

**Comment by ShrillShrestha** [comment]
@cduck, Can you please guide me on how can I perform the test? I couldn't find the procedure in `CONTRIBUTING.md` file.

**Comment by cduck** [comment]
Perform what test?  Maybe @balopat can advise on current continuous integration advice.

**Comment by ShrillShrestha** [comment]
Maybe I can issue a PR, and you can suggest me some changes if I have do something different.
