### ISSUE TITLE
'setup.py install' doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [quantumlib/Cirq#4353]
**Description of the issue**
```setup.py install' doesn't install any files

I am trying to create the FreeBSD port, but the plist is empty:
```
$ make makeplist
/you/have/to/check/what/makeplist/gives/you
%%PYTHON_SITELIBDIR%%/cirq-0.11.0-py%%PYTHON_VER%%.egg-info/PKG-INFO
%%PYTHON_SITELIBDIR%%/cirq-0.11.0-py%%PYTHON_VER%%.egg-info/SOURCES.txt
%%PYTHON_SITELIBDIR%%/cirq-0.11.0-py%%PYTHON_VER%%.egg-info/dependency_links.txt
%%PYTHON_SITELIBDIR%%/cirq-0.11.0-py%%PYTHON_VER%%.egg-info/requires.txt
%%PYTHON_SITELIBDIR%%/cirq-0.11.0-py%%PYTHON_VER%%.egg-info/top_level.txt
```


**Cirq version**
0.11.0

**Comment by balopat** [comment]
Thanks for opening - note, we switched to a monorepo structure:

./setup.py - defines the cirq metapackage, which is an empty package that defines the dependency list for all the cirq modules
./cirq-core/setup.py - cirq core 
./cirq-pasqal/setup.py - cirq-pasqal
...

etc. 

You have to decide which one do you want to install.

**Comment by yurivict** [comment]
Please note that GitHub tarball for ```0.11.1``` doesn't contain ```cirq-pasqal```, ```cirq-ionq```, etc.

**Comment by balopat** [comment]
@yurivict, yes because it was a patch release on top of 0.11.0 which only had cirq-google and cirq-core. We cherry-picked a single commit to fix the JSON serialization backwards compatibility issue with cirq.TrialResult. The extraction of cirq-pasqal, ionq, etc. were done after 0.11.0 on the `master` branch which we will cut for the 0.12.0 release in a couple of weeks.

**Comment by yurivict** [comment]
Ok, thanks!
