### ISSUE TITLE
cirq.kraus seems to fail on PhasedXZGate

### ISSUE THREAD

**Issue by dkafri** [quantumlib/Cirq#4434]
**Description of the issue**
I get a TypeError when using cirq.kraus on this gate.
**How to reproduce the issue**

```python
import cirq

op = cirq.PhasedXZGate(axis_phase_exponent=-0.5,
                           x_exponent=-0.5,
                           z_exponent=1).on(cirq.GridQubit(3, 3))
cirq.kraus(op)
```
Produces:
```
Traceback (most recent call last):
  File "/usr/local/google/home/dkafri/.config/JetBrains/PyCharmCE2021.2/scratches/scratch_62.py", line 6, in <module>
    cirq.kraus(op)
  File "/usr/local/google/home/dkafri/.virtualenvs/pyle/lib/python3.8/site-packages/cirq/protocols/kraus.py", line 189, in kraus
    raise TypeError(
TypeError: object of type '<class 'cirq.ops.gate_operation.GateOperation'>' does have a _kraus_, _mixture_ or _unitary_ method, but it returned NotImplemented.
```

**Cirq version**
I get this error both for `0.12.0.dev20210630205305` and `0.12.0`

**Comment by maffoo** [comment]
Seems like this is an error in the `kraus` protocol; it should call `cirq.unitary` to get the unitary representation of the object in question, rather than looking for a `_unitary_` method directly, because `PhasedXZGate` does work with the unitary protocol:
```
In [1]: import cirq
   ...: 
   ...: op = cirq.PhasedXZGate(axis_phase_exponent=-0.5,
   ...:                            x_exponent=-0.5,
   ...:                            z_exponent=1).on(cirq.GridQubit(3, 3))
   ...: cirq.unitary(op)
Out[1]: 
array([[ 0.5-0.5j, -0.5+0.5j],
       [-0.5+0.5j, -0.5+0.5j]])
```
We could also implement `_unitary_` directly on `PhasedXZGate`; currently it has to decompose the gate to get the unitary.

**Comment by tanujkhattar** [comment]
I see the same issue in mixtures as well
```python
In [1]: import cirq
   ...: op = cirq.PhasedXZGate(axis_phase_exponent=-0.5,
   ...:                            x_exponent=-0.5,
   ...:                            z_exponent=1).on(cirq.GridQubit(3, 3))
   ...: print(cirq.has_mixture(op))
   ...: cirq.mixture(op)
True
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-fe586f2b45b8> in <module>
      4                            z_exponent=1).on(cirq.GridQubit(3, 3))
      5 print(cirq.has_mixture(op))
----> 6 cirq.mixture(op)

~/opt/anaconda3/envs/cirq/lib/python3.8/site-packages/cirq/protocols/mixture_protocol.py in mixture(val, default)
     99         raise TypeError(f"object of type '{type(val)}' has no _mixture_ or _unitary_ method.")
    100
--> 101     raise TypeError(
    102         "object of type '{}' does have a _mixture_ or _unitary_ "
    103         "method, but it returned NotImplemented.".format(type(val))

TypeError: object of type '<class 'cirq.ops.gate_operation.GateOperation'>' does have a _mixture_ or _unitary_ method, but it returned NotImplemented.
```

The problem is that `has_[kraus|mixture]` methods check only for `_has_[kraus|mixture]_`  member functions and then fallback on `kraus/mixture` methods to check for `_kraus_ | _mixture_`. However, the former has a `allow_decompose` argument but the latter doesn't. 

I can send a PR to fix this but I have a question -- do we need a `allow_decompose` argument in `kruas`, `mixture` protocols? `unitary` protocol doesn't have the `allow_decompose` argument even though `has_unitary` does, but they both work fine because `has_unitary` doesn't depend on `unitary` as a fallback.

**Comment by tanujkhattar** [comment]
Note that simply using `cirq.unitary` instead of checking for `_unitary_` is not enough. In `has_kraus`, we check whether `all(has_kraus(val) for val in decomposed_operations)` then the primary operation also `has_kraus`. Therefore, in the `kraus` method, we will need to recursively compute the `kraus` of all decomposed operations and combine their `kraus` operators by serial concatenation. 

This will be useful, for eg, to automatically compute the kraus operators of a `PauliMeasurementGate` (requested in #4127) which decomposes into pauli operations + measurement gate -- both of which have different types of kraus operators (unitary vs measurement).

**Comment by 95-martin-orion** [comment]
This is a duplicate of #3965, which came to a similar conclusion (add `allow_decompose` to `kraus`/`mixture`). It's important to note that limits must be placed on this decomposition, as number of Kraus operators / mixture elements can exponentially explode.
