### ISSUE TITLE
pylint checker for copyright notices

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4564]
**Description of the issue**
Maybe pylint could automatically check for copyright notices instead of reviewers needed to keep an eye out. Inspired by https://github.com/quantumlib/Cirq/pull/456.

Look into https://stackoverflow.com/questions/51886592/can-pylint-check-for-a-static-comment-copyright-notice-at-the-top-of-all-docum

**Comment by yjt98765** [comment]
A 'raw checker' should be able to check it. Can you assign the task to me?

**Comment by yjt98765** [comment]
> @yjt98765 Assigned.

Thank you!

As shown in [this](https://pylint.pycqa.org/en/latest/how_tos/custom_checkers.html) example, we need to assign an id (a letter + 4 digits) to the message. Since no custom checkers have been used in this project, we should come up with a rule for this, especially for the numbers (e.g., they are sequential numbers with prefix 00 or 99). The letter is one of C, W, E, F, and R, standing for Convention, Warning, Error, Fatal, and Refactoring. I guess the proper one for the copyright notice would be E as it has to be there. What do you think?

**Comment by yjt98765** [comment]
> Thanks for the recommendation @ronnie-llamado . We prefer to leverage tools we already have like pylint for these cases because Cirq contains too many dependencies as it is.

It seems that the tool can be applied to many types of files, while pylint can only check python files. In this project, Some (if not all) of the bash scripts, TypeScript files, and Jupyter Notebooks also contain a copyright notice.

However, if only one type of copyright is adopted here, applying that tool seems like overkill. It complicates the checking process and increases external dependency.

**Comment by MichaelBroughton** [comment]
This functionality is in now.
