### ISSUE TITLE
Move cirq/ops/moment.py to cirq/circuits/moment.py ? 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4665]
**Description of the issue**
Moments are a building blocks for circuits and should belong in the cirq/circuits/* instead of cirq/ops/*. This issue is to discuss this proposal and, if agreed, move the files following a deprecation cycle.

```
0.13.0.dev
```

**Comment by tanujkhattar** [comment]
Similarly, should we move `cirq/circuits/circuit_operation.py` to `cirq/ops/circuit_operation.py` ?

**Comment by maffoo** [comment]
Moving `Moment` into `cirq.circuits` seems fine to me; would we even need a deprecation cycle since the supported way of accessing this is `cirq.Moment`, which won't change? It might be worth clarifying our deprecation policy around internal refactors like this (or maybe this is already spelled out in which case ignore my comment :-) ).

One consideration here is reducing circular imports. We already have workaround in place for circular imports in [`moment.py`](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/ops/moment.py#L43) and moving it into `cirq.circuits` should fix that. On the other hand, moving `CircuitOperation` into `cirq.ops` would introduce more such circular imports, so I think we should avoid doing that. Also, `CircuitOperation` seems more closely related to circuits to me, since its main point is to introduce structure into circuits, rather than to be a fundamental operation like textbook gates.

It looks We have a few other circular imports between `cirq.ops` and `cirq.circuits` such as in [`gateset.py`](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/ops/gateset.py#L335) so we might want to consider if there are other things that could be refactored to reduce these (instead of lazy loading).

**Comment by tanujkhattar** [comment]
> would we even need a deprecation cycle since the supported way of accessing this is cirq.Moment, which won't change

I think we should go through a deprecation cycle to avoid breaking all code of the form:
```python
>>> from cirq.ops import Moment
>>> import cirq.ops as ops
>>> ops.Moment()
```

**Comment by 95-martin-orion** [comment]
+1 to Matthew's comments on circular imports - `CircuitOperation` lives in `cirq.circuits` for exactly the reason he describes. Also, references to `Moment` in `cirq.ops` and `cirq.devices` (`OP_TREE` and `NoiseModel` being the primary culprits) would become circular imports as a part of this change, so we'd need to add lazy loading to prevent those.

**Comment by maffoo** [comment]
Are `OP_TREE` and `NoiseModel` used outside of type annotations? If only needed for type annotations the imports should be in `if TYPE_CHECKING` blocks to avoid runtime circular imports (and in fact, they should use top-level imports like `cirq.OP_TREE`).

**Comment by tanujkhattar** [comment]
Discussed:

- Let's move moment and not move circuit ops.
