### ISSUE TITLE
Add an option to highlight a subset of qubits in cirq.Heatmap 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4691]
**Is your feature request related to a use case or problem? Please describe.**

**Describe the solution you'd like**
Heatmaps are often useful to visualize error metrics for qubits and couplers on the google devices. When selecting a subset of qubits to run an experiment on; it's useful to consult heatmaps of error metrics. We should add an option to the `cirq.Heatmap` and `cirq.TwoQubitInteractionHeatmap` so that we can pass in a list of qubits and highlight it on the heatmap. For example:

![image](https://user-images.githubusercontent.com/7863287/142082368-38550608-0615-4519-9029-249d37a0bc33.png)

This can be done right now by manually specifying a different edge width and color for the selected qubits. For example: 
```python
fig, ax = plt.subplots(figsize=(12, 10))
edge_colors = tuple('red' if q in selected_qubits else 'grey' for q in device.qubits)
linestyle = tuple('solid' if q in selected_qubits else 'dashed' for q in device.qubits)
linewidths = tuple(4 if q in selected_qubits else 2 for q in device.qubits)
cirq.Heatmap({q: 0.0 for q in device.qubits}).plot(
    ax=ax,
    collection_options={
        'cmap': 'binary',
        'linewidths': linewidths,
        'edgecolors': edge_colors,
        'linestyles': linestyle,
    },
    plot_colorbar=False,
    annotation_format=None,
)
heatmap._plot_on_axis(ax)
fig.show()
```

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P1 - I need this no later than the next release (end of quarter)

**Comment by kris524** [comment]
Hello all, Is this still a needed feature?

**Comment by tanujkhattar** [comment]
@kris524 Yes, the feature is still needed and we would appreciate help!

**Comment by kris524** [comment]
Awesome! I will take it

**Comment by kris524** [comment]
Just to make it clear. We want to get something like this:
`cirq.Heatmap({q: 0.0 for q in device.qubits}).plot(
    ax=ax,
    selected_qubits = ...
    collection_options={
        'cmap': 'binary',
    },
    plot_colorbar=False,
    annotation_format=None,
)`
to reach the objective, correct? Also, what will the default values for `edge_colors, linestyle, linewidths` inside `collection_options`  be? Will they be `None` or thos `grey, dashed, 2` 

I think it has to be `None` because otherwise, we will always have this grid (without the red bit). But let me know what you think

**Comment by kris524** [comment]
One last question: Could you suggest a method for `PolyCollection` or something that could help me get the data in `collection_options`? This is for testing purposes (I want to compare the expected vs returned contents of `linewidths edge_colors linestyle`)

**Comment by NoureldinYosri** [comment]
@AbdullahKazi500 please refer to our [dev guidlines](https://github.com/quantumlib/Cirq/blob/543d9cd4f478805a759fc48cacccd1ea60a145c4/docs/dev/development.md) for how to modify, test and create PRs 

---
I will go ahead and close https://github.com/quantumlib/Cirq/pull/6635 https://github.com/quantumlib/Cirq/pull/6634 https://github.com/quantumlib/Cirq/pull/6629 https://github.com/quantumlib/Cirq/pull/6625 so that moderators don't get spammed.

---
please create as single PR with your modififcations to `cirq-core/cirq/vis/heatmap.py` and `cirq-core/cirq/vis/heatmap_test.py`. The PR should have the generated plots so that we can check that they do what we need. as it's the plots you shared above don't make sense to me and don't like what Tanuj shared in the description above.

---
For UnitaryHack participants, as per the [hackaton's rules](https://unitaryhack.dev/rules/) this issue is till up for grabs

**Comment by Yash-10** [comment]
> For UnitaryHack participants, as per the [hackaton's rules](https://unitaryhack.dev/rules/) this issue is till up for grabs

@NoureldinYosri I am working on this issue and created #6642 and would like to be assigned if the PR is successfully merged. Thanks!

**Comment by NoureldinYosri** [comment]
reopening and then closing after correcting the assignee so that unitaryhack's automation can pick this up
