### ISSUE TITLE
Gateset containership, subcircuits with negative reps

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#4727]
**Description of the issue**

Subcircuits allow negative repetitions, which cause each gate to be inverted. This inversion is not performed when gatesets iterate the subcircuit.

**How to reproduce the issue**

```python
def test_gateset_contains():
    gate = cirq.XPowGate(exponent=0.5)
    gateset = cirq.Gateset(gate)
    op = cirq.CircuitOperation(cirq.FrozenCircuit(gate.on(cirq.LineQubit(0))), repetitions=-1)

    # This should not pass, because the gates are XPow(-0.5), but it does
    assert op in gateset

    # This (correctly) fails.
    for inner_op in op.mapped_circuit().all_operations():
        assert inner_op in gateset
```
**Cirq version**
0.14.0.dev

**Comment by daxfohl** [comment]
Kind of annoyingly, one could even populate the gateset with the specific measurement gates (with measurement key repetition id prefixes) and it will fail unless the subcircuit is fully unrolled (including repetitions). Or maybe unrolling it completely is just the right thing to do.

**Comment by maffoo** [comment]
Personally, I think negative reps is a bit of a misfeature and could be removed. It seems to me that "inverting a circuit" is a big operation that should not be hidden behind a sign in the number of repetitions.

**Comment by tanujkhattar** [comment]
Discussion on original PR regarding this: https://github.com/quantumlib/Cirq/pull/4491#discussion_r706509404

Worth revisiting it again now. cc @95-martin-orion

**Comment by 95-martin-orion** [comment]
From discussion on the Cirq sync: the issue exists in the interaction of Gateset and CircuitOperation. As @daxfohl suggests, the correct behavior would be to fully unroll the CircuitOperation to correctly identify the operations it contains.

> Personally, I think negative reps is a bit of a misfeature and could be removed. It seems to me that "inverting a circuit" is a big operation that should not be hidden behind a sign in the number of repetitions.

Supporting negative repetitions is convenient for recursively-defined circuits, where a given `CircuitOperation` may need to be inverted multiple times before finally being executed. That said, I don't have an example of such a use case offhand (and such cases are likely at the edge of NISQ anyways), so I'm not deeply opposed to removing the behavior in favor of readability. That said, I think that change is separate from the issue here.
