### ISSUE TITLE
[cirq_web 3D circuit] X**0.5 and Y**0.5 look the same as X and Y

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4761]
**Description of the issue**

The default look for `X**0.5` and `Y**0.5` look the same as `X` and `Y` in the 3D circuit.

**How to reproduce the issue**

```
import cirq_web
a, b, c, d = cirq.GridQubit.rect(2, 2)
cirq_web.Circuit3D(cirq.Circuit(cirq.X(a)**0.5, cirq.Y(b)**0.5, cirq.X(c), cirq.Y(d))).generate_html_file(
    file_name="hello.html")
```

![image](https://user-images.githubusercontent.com/635073/146627925-5158d61f-670b-41c7-a876-bfa41377fa0a.png)

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

0.13.1

**Comment by yjt98765** [comment]
The problem is that the symbols on the boxes are generated entirely based on `wire_symbols`:

https://github.com/quantumlib/Cirq/blob/4ebfb1c8fa123ec6164ff8102b69858ac868840f/cirq-web/cirq_web/circuits/circuit.py#L86-L91

As a comparison, the text representation of a circuit also consider the exponent:

https://github.com/quantumlib/Cirq/blob/4ebfb1c8fa123ec6164ff8102b69858ac868840f/cirq-core/cirq/circuits/circuit.py#L2468-L2474

May I be assigned with this issue? I guess `cirq-web` can generally follow the same pattern.
