### ISSUE TITLE
cg.get_engine_sampler gate_set_name should be made optional

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#5132]
As far as I can tell, `Engine.get_sampler`'s `gate_set` argument is now optional. As such, `cg.get_engine_sampler` should not require a gate_set_name.

Also: we don't have a CZ gate in `gatesets.NAMED_GATESETS` or `GOOGLE_GATESETS`

**Comment by maffoo** [comment]
We could deprecate `cg.get_engine_sampler` entirely, since this is equivalent to `cg.get_engine(...).get_processor(...).get_sampler()`. But I agree if we keep it around we should make the gate set arg optional, as it is on [`EngineProcessor.get_sampler`](https://github.com/quantumlib/Cirq/blob/master/cirq-google/cirq_google/engine/engine_processor.py#L104).

**Comment by mpharrigan** [comment]
This has been done
