### ISSUE TITLE
Can you please create even a ruby version of this framework so that the innovative idea and the project will not be available to just one community of interest ?

### ISSUE THREAD

**Issue by Ash-the-practical-programmer** [quantumlib/Cirq#5266]
**Can such a project even be created/implemented in Ruby so that the innovative idea and project will not just be limited to just one community of interest ?**

**Please try to implement even a ruby version as there is also a big community of rubyists who don't wanna be devoid of it .**

P0 - this should land no later than a month
P1 - I need this no later than the next release (end of quarter)
P2 - we should do it in the next couple of quarters 
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion

**Comment by vtomole** [comment]
Hey @Ash-the-practical-programmer,
 
Thanks for this question. 

After a quick search of quantum programming frameworks in Ruby, i haven't been able to find anything of note. This might be because Ruby isn't big into scientific computing like Python is.  Are there easy ways to interoperate with Python code in Ruby?

**Comment by vtomole** [comment]
Hey again @Ash-the-practical-programmer. We might be able to do this by having [quantum_ruby](https://github.com/AlessandroMinali/quantum_ruby) export QASM and use Cirq's [QASM importer](https://quantumai.google/cirq/interop) to consume the generated QASM.  Maybe there is a way to transpile [cirq-web](https://github.com/quantumlib/Cirq/tree/master/cirq-web) to Ruby. Since i don't know Ruby, I've assigned this issue to you.

**Comment by vtomole** [comment]
@Ash-the-practical-programmer Please re-open this issue once you confirm that you are looking into this.
