### ISSUE TITLE
KnownMatrixGate should automatically implement inverse

### ISSUE THREAD

**Issue by babbush** [quantumlib/Cirq#536]
One should not be forced to define EigenGate to have basic gate functionality in Cirq. 99.9% of users will never raise a gate to a fractional power and will find EigenGate terribly confusing. However, taking the inverse of a gate should be simple and should not require EigenGate. In the case of KnownMatrixGate, the gate inverse should be inferred directly from the matrix.

**Comment by dabacon** [comment]
This issue is stale as these gate classes no longer exist (pre protocols).  We have a `__pow__` protocol and `MatrixGate` implements it by default.

However +1 to users not using powering of gates, we should really audit some code to see how useful powering is, a lot of the research code I have looked at does not use this.
