### ISSUE TITLE
Remove ion device tutorial?

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5463]
**Description of the issue**

In #5326 the question was raised as to whether to get rid of the ion device tutorial.  Filing this to discuss.

**Comment by dabacon** [comment]
@augustehirth @dstrain115 opinions?

**Comment by augustehirth** [comment]
If, at its core, it is presenting functionality that doesn't exist in cirq any more, definitely cut it. 
If it is the only documentation we have for a certain aspect of cirq, I think we should keep it even if it is a bit out of date. 
Otherwise, would it be doable to update without too many changes?

**Comment by MichaelBroughton** [comment]
The decision here: #2793 was to move ions and neutral atoms functionality out into their respective vendors (with some things getting outright cut) and then re-introduce them into cirq-core if we had more than one vendor who was making use of them. With this in mind I think we should remove these tutorials from core Cirq and move whatever makes sense from these tutorials into vendor tutorials (if it makes sense to do so). I see this and #5521 as clear things to delete and then if possible beef up vendor tutorials.
