### ISSUE TITLE
Gateset: fails to accept an operation if the gate type matches multiple GateFamilies in the gateset.

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#5543]
**Description of the issue**
`Gateset.__contains__()` should continue to check other GateFamilies instead of failing when the operation matches the instance type but isn't accepted by the current GateFamily being checked.

**How to reproduce the issue**
The order of GateFamilies matter here; flipping them will make it succeed.

```python
gs = cirq.Gateset(cirq.GateFamily(cirq.ZPowGate, tags_to_accept=[cirq_google.PhysicalZTag()]), cirq.GateFamily(cirq.ZPowGate, tags_to_ignore=[cirq_google.PhysicalZTag()]))
op = cirq.Z(q).with_tags(cg.PhysicalZTag())
op in gs
```

<details>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/cxing/proj/Cirq/cirq-core/cirq/ops/gateset.py", line 487, in __contains__
    assert item in self._type_gate_families[gate_mro_type], (
AssertionError: Z type <class 'cirq.ops.common_gates.ZPowGate'> matches Type GateFamily:Type GateFamily: cirq.ops.common_gates.ZPowGate
Accepts `cirq.Gate` instances `g` s.t. `isinstance(g, cirq.ops.common_gates.ZPowGate)`
Ignored tags: [cirq_google.PhysicalZTag()] but is not accepted by it.
```
</details>

**Cirq version**
Cirq head before 0.15 release

cc @tanujkhattar

**Comment by tanujkhattar** [comment]
`Gateset.__contains__` does two checks: 
1. An O(1) check of whether the gate matches an instance or type gate family 
2. An O(N) check of whether the gate matches any gate family. 

The O(1) check assumes that the type and instance gate families do trivial `isinstance(g, gate_type)` or `g == gate_instance` checks. This was true before `tags_to_accept` and `tags_to_ignore` flags were added to the base GateFamily class. 

Now, because of tags_to_accept / tags_to_ignore; the default type and instance gate families also have the additional complexity of dealing with tags; and hence should be considered equivalent to custom gate families (i.e. do an O(N) check instead of O(1) check). 

I've sent a PR to fix this. PTAL.
