### ISSUE TITLE
Qasm output decomposes CNOT**-1 instead of using the native gate

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#5692]
```
import cirq

c = cirq.Circuit(
    cirq.CX(cirq.LineQubit(0), cirq.LineQubit(1)),
)
print(cirq.inverse(c).to_qasm())
```

Outputs:

```
// Generated from Cirq v0.15.0

OPENQASM 2.0;
include "qelib1.inc";


// Qubits: [q(0), q(1)]
qreg q[2];


// Gate: CNOT**-1.0
ry(pi*-0.5) q[1];
u3(pi*0.5,0,pi*1.25) q[0];
u3(pi*0.5,pi*1.0,pi*1.75) q[1];
sx q[0];
cx q[0],q[1];
rx(0) q[0];
ry(pi*0.5) q[1];
cx q[1],q[0];
sxdg q[1];
s q[1];
cx q[0],q[1];
u3(pi*0.5,pi*1.25,pi*1.0) q[0];
u3(pi*0.5,pi*0.75,0) q[1];
ry(pi*0.5) q[1];
```

Should output:

```
// Generated from Cirq v0.15.0

OPENQASM 2.0;
include "qelib1.inc";


// Qubits: [q(0), q(1)]
qreg q[2];


cx q[0],q[1];
```

**Comment by viathor** [comment]
Circuit simplifications might not affect unitary interpretation of a circuit, but do affect its noisy interpretation. For this reason, cirq's NISQy philosophy calls for circuit simplifications to only be done when explicitly requested by the user. This places a constraint on possible solutions to this issue. Namely, we don't wish to do any algebra in serde, qasm conversion and other similar code. See [this comment](https://github.com/quantumlib/Cirq/pull/5730#discussion_r919460319) for a concrete example how doing otherwise may harm our users.

**Comment by dabacon** [comment]
Discussed this at Cirq Cync.

The main issue is that is that in Cirq we have tended to interpret the exponent as different gate, i.e. CNOT and CNOT**-1 are actually different physical transforms.   QASM does not have an CNOT_INV or a parameterized CNOT gate, so it doesn't make sense to serial to this.  Note that this is different that CZ where the QASM version of the gate has a parameter.

If you want to handle this case the recommended way is the write a transformer that transforms inverse cnots to cnots in your circuit.
