### ISSUE TITLE
`plot_state_histogram` and `plot_density_matrix` not attributes of module `cirq`

### ISSUE THREAD

**Issue by Shuhul24** [quantumlib/Cirq#5989]
**Description of the issue**
Module `cirq` does not have attributes `plot_state_histogram` and `plot_density_matrix`.
**How to reproduce the issue**

```python
simulator = cirq.DensityMatrixSimulator()
q0 = cirq.GridQubit(1, 0)
q1 = cirq.GridQubit(1, 1)
def basic_circuit(meas=True):
    sqrt_x = cirq.X**0.5
    yield cirq.H(q0)
    yield cirq.CNOT(q0, q1)
    if meas:
        yield cirq.measure(q0, key='q0'), cirq.measure(q1, key='q1')

circuit = cirq.Circuit()
circuit.append(basic_circuit())
print(cirq.unitary(circuit))
cirq.plot_density_matrix(cirq.unitary(circuit))
result = simulator.run(circuit, repetitions=100)
_ = cirq.plot_state_histogram(result, plt.subplot())
plt.show()
```

<details>

put long logs in details blocks *like this*

</details>

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

0.13.1

**Comment by tanujkhattar** [comment]
This is because you are using an older version of Cirq (`v0.13.1`). You can use `cirq.vis.plot_state_histogram` instead in `v0.13.1`. 

Another option would be to consider upgrading Cirq to the latest version via `pip install --upgrade cirq`. Note that the plot functions were moved to cirq namespace in https://github.com/quantumlib/Cirq/pull/4752 which was released as part `v0.14.0`: https://github.com/quantumlib/Cirq/releases/tag/v0.14.0

I will close this issue now. Please let me know if you have any further questions.
