### ISSUE TITLE
`MatrixGate` names don't survive serialization

### ISSUE THREAD

**Issue by richrines1** [quantumlib/Cirq#5999]
**Description of the issue**

`_name` is excluded from `MatrixGate._json_dict_()` and so is reset to `None` by serialization+deserialization

**How to reproduce the issue**

```python
gate = cirq.MatrixGate(np.eye(2), name="name")
gate_after_serialization = cirq.read_json(json_text=cirq.to_json(gate))

print(gate._name)  # "name"
print(gate_after_serialization._name)  # None
```

**Cirq version**

```
1.2.0.dev20230105212249
```

**Comment by dstrain115** [comment]
Accepted, though we have to be careful that old jsons without names are still deserialized.

**Comment by mustapha-saad-codeStar** [comment]
What are the deliverables precisely required here?

**Comment by tanujkhattar** [comment]
@mustapha-saad-codeStar We want to update `MatrixGate._json_dict_` method to also include the `name` attribute in json serialization, if the `name` is not None. This should be backwards compatible because deserializing a matrix gate without a name should work as expected as `name` has a default value of `None`.
