### ISSUE TITLE
cirq.sample_state_vector fails when the number of qubits > 32

### ISSUE THREAD

**Issue by rht** [quantumlib/Cirq#6031]
**Description of the issue**

I use the `cirq.sample_state_vector` to extract counts from the statevector. But it appears to not scale beyond 32 qubits due to a NumPy limitation, which hardcodes the maximum number of dimensions to be 32: https://github.com/numpy/numpy/issues/5744.

**How to reproduce the issue**

I'm running the following code in an NVIDIA cuQuantum Docker instance, because a CPU simulation of the code would be slow. However, this shouldn't affect that the error still happens.
```python
import cirq
import qsimcirq

gpu_mode = 2
options = qsimcirq.QSimOptions(gpu_mode=gpu_mode)
simulator = qsimcirq.QSimSimulator(options)

n = 33
qc = cirq.Circuit()
qs = cirq.LineQubit.range(n)
for i in range(n):
    qc.append(cirq.H(qs[i]))
    qc.append(cirq.measure(qs[i]))

result = simulator.simulate(qc)
sv = result.final_state_vector
cirq.sample_state_vector(sv, range(n))
```

Error message:
```
Traceback (most recent call last):
  File "cirq_huge_circuit.py", line 21, in <module>
    cirq.sample_state_vector(sv, range(n))
  File "/opt/conda/lib/python3.8/site-packages/cirq/sim/state_vector.py", line 214, in sample_state_vector
    probs = _probs(state_vector, indices, shape)
  File "/opt/conda/lib/python3.8/site-packages/cirq/sim/state_vector.py", line 322, in _probs
    tensor = np.reshape(state, qid_shape)
  File "<__array_function__ internals>", line 180, in reshape
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: maximum supported dimension for an ndarray is 32, found 33
```

**Cirq version**

```
cirq-core 0.14
```
But should apply to 1.1.x as well: https://github.com/quantumlib/Cirq/blob/8b97aa5d8f90d48e41dabaddf3c2b56ec1d2bddd/cirq-core/cirq/sim/state_vector.py#L326-L354. `np.reshape` is not the only operation that has the <=32 dimension constraint.

**Comment by verult** [comment]
From Cirq sync:

- Need to investigate feasibility of alternative solutions that do not have the limit of 32

**Comment by NoureldinYosri** [comment]
The 32 limit seems interinsic to numpy, but it seems there are multiple scientific libraries running into this problem so numpy might pump up that limit https://github.com/numpy/numpy/issues/5744#issuecomment-1486059824 , however it probably won't be easy for them https://github.com/numpy/numpy/issues/5744#issuecomment-89718887 and will take time.

The code in this issue can be rewritten in a way that doesn't require reshaping the state array, however this is not an isolated issue and we will get more occurrences of it in other places as people build larger circuits/run simulations on large GPUs. 

For now I think it will be enough to write helper functions that allow us to do the needed operations but on a flattened array instead of a reshaped array. For a start a function for indexing and trasposing will be needed to fix this issue.

---

An alternative would be to increase the limit yourself, build a local version of numpy (and hope it works fine) as mentioned  in https://stackoverflow.com/a/35192754

**Comment by rht** [comment]
Update: I found another maximum supported dimension issue in https://github.com/quantumlib/Cirq/blob/16ed00d39d186f4d5c822747a60ceac79d630a28/cirq-core/cirq/sim/state_vector_simulation_state.py#L79.
```
Traceback (most recent call last):
  File "/home/rht/oom.py", line 11, in <module>
    sim.simulate(qc_cirq)
  File "/home/rht/.local/lib/python3.9/site-packages/cirq/sim/simulator.py", line 495, in simulate
    return self.simulate_sweep(
  File "/home/rht/.local/lib/python3.9/site-packages/cirq/sim/simulator.py", line 510, in simulate_sweep
    return list(self.simulate_sweep_iter(program, params, qubit_order, initial_state))
  File "/home/rht/.local/lib/python3.9/site-packages/qsimcirq/qsim_simulator.py", line 529, in simulate_sweep_iter
    final_state = cirq.StateVectorSimulationState(
  File "/home/rht/.local/lib/python3.9/site-packages/cirq/sim/state_vector_simulation_state.py", line 350, in __init__
    state = _BufferedStateVector.create(
  File "/home/rht/.local/lib/python3.9/site-packages/cirq/sim/state_vector_simulation_state.py", line 79, in create
    state_vector = initial_state.reshape(qid_shape)
ValueError: maximum supported dimension for an ndarray is 32, found 34
```

The code I used to reproduce this is the one in https://github.com/quantumlib/qsim/issues/612#issue-1716537877, but with `num_qubits` of 34. This time, I'm using Cirq 1.1.0. I suppose this `initial_state.reshape(qid_shape)` is not present in Cirq 0.14, and hence why I didn't encounter this error when posting this issue (#6031).

**Comment by rht** [comment]
I suppose `cirq.sample_state_vector` is not commonly used, but the new error I wrote in https://github.com/quantumlib/Cirq/issues/6031#issuecomment-1562273132 has a code pattern that is very commonly used. As such, this affects cuQuantum Appliance 23.03 (which uses Cirq 1.0.0), when using the cuStateVec backend (cuTensorNet should be unaffected); cc: @leofang @ahehn-nv @tlubowe.

**Comment by NoureldinYosri** [comment]
from a first glance it seems that the reshape is not actually needed ... the `qid_shape` is passed anyway to other functions and isn't actually used except during the calculation of probabilities which I fix in #6090 so after that PR is merged I think we can remove the reshape line and it will still work -maybe with a few tweeks-.

**Comment by leofang** [comment]
It does not make any sense to be limited by NumPy's arbitrary choice (32 or whatever). For single-node workloads the only true limitation is the 64-bit unsigned integer limit, which translates to 64 qubits, and for multi-node workloads, unlimited in practice since the state vector can be processed/stored in a distributed manner (cuQuantum has that). Also, other simulation methods like tensor network allow exceeding 64 qubits very easily, so I would advice for all QC frameworks to not make any assumptions in the max number of qubits.

**Comment by hthayko** [comment]
Hi there - any updates on the cirq 1.1.0 issue? 
Basically the new cirq doesn't allow >32 qubit simulations. I would say this is a pretty serious issue.

**Comment by NoureldinYosri** [comment]
The https://github.com/quantumlib/qsim simulator has no limit on the number of qubits of the simulation. As long as you have enough RAM the qsim simulator will run the simulation with no problem. 


With this I will close this issue since we have an alternative simulator that handles more than 32 qubits and the limitation imposed on the state vector simulator comes from numpy and is not intrinsic to the state vector simulator.

**Comment by rht** [comment]
You should check the code in https://github.com/quantumlib/Cirq/issues/6031#issuecomment-1562273132. I used `qsimcirq` there.

**Comment by NoureldinYosri** [comment]
@rht As said before this is a numpy issue and isn't internsic to the simulators ... if we do it in a different way then we are sacrificing efficiency and by that I mean multiplying the run time by several orders of magnitude. not to mention filling our code base with throwaway code.

When numpy starts supporting more than 32 dimensions then the state vector simulation will work out of the box.  If you really need to do this kind of simulation then I suggest keeping an eye on the numpy issue https://github.com/numpy/numpy/issues/5744 where they indicated that they don't have an issue with this but are lacking people to work on the fixing blockers for this, mainly the old iterators https://github.com/numpy/numpy/issues/5744#issuecomment-1614708534

**Comment by NoureldinYosri** [comment]
@rht at your risk and as a work around you can compile your own numpy after updating the limit on number of dimensions https://github.com/numpy/numpy/issues/5744#issuecomment-1614831105

**Comment by NoureldinYosri** [comment]
@rht does https://github.com/quantumlib/qsim/pull/623 work for you?

**Comment by rht** [comment]
Yes, it looks promising, that I can finally use `sim.simulate(circuit)` for >32 qubits. A 1D array result works for me.

**Comment by NoureldinYosri** [comment]
@rht qsim simulator now has a new method `simulate_into_1d_array` which you can use to run your simulation and get the state vector as a 1D array.

**Comment by rht** [comment]
Yes, thank you so much for the `simulate_into_1d_array`!
