### ISSUE TITLE
cirq.measure_pauli_string rejects negated pauli strings

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#6137]
```
import cirq
cirq.measure_single_paulistring(-cirq.Y(cirq.LineQubit(0))*cirq.Y(cirq.LineQubit(1)), key='1')
```

**Comment by tanujkhattar** [comment]
This should be fairly straightforward to fix.  We raise an error if the pauli string is does not have a coefficient of 1 here - https://github.com/quantumlib/Cirq/blob/9a1609ce8800ed1aa82bbf6261f5f7b8a41b81cf/cirq-core/cirq/ops/measure_util.py#L55

However, the underlying `PauliMeasurementGate` does support `DensePauliString`s with coefficient +1 and -1. So, instead of passing `pauli_observable.values()` to construct the `PauliMeasurementGate`, we can just pass `pauli_observable.dense(pauli_observable.keys())` and then remove the check for coefficient being exactly +1. 

https://github.com/quantumlib/Cirq/blob/9a1609ce8800ed1aa82bbf6261f5f7b8a41b81cf/cirq-core/cirq/ops/measure_util.py#L60

**Comment by skushnir123** [comment]
I can take this issue.
