### ISSUE TITLE
`cirq.dirac_notation` can't handle qudits when `qid_shape` is not passed in.

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#6165]
**How to reproduce the issue**

```python
import cirq
import numpy as np

state_vector = np.array([0, 0, 1], dtype=np.complex64)


print(cirq.dirac_notation(state_vector))
# prints
# 0

```
The correct result should be

`|2⟩`

**Cirq version**
`main`  branch version

**Comment by jeeva2812** [comment]
Isn't printing 0 the expected behaviour, given that dirac_notation is considered it to be a qubit unless qid_shape is explicitly mentioned - [Code Pointer](https://github.com/quantumlib/Cirq/blob/98496955af1c27906d85b016f6db9f283e687795/cirq-core/cirq/qis/states.py#L710)

We could give a warning when the shape is not a power of 2, when qid_shape is not provided.  On that note, there could be an error handling in place when the provide qid_shape and state vector is not compatible as well. Thoughts?

**Comment by vtomole** [comment]
> Isn't printing 0 the expected behaviour, given that dirac_notation is considered it to be a qubit unless qid_shape is explicitly mentioned

Yes, this issue was created in cases where the caller doesn't have access to a `qid_shape`. I've re-titled the issue appropriately. 

> We could give a warning when the shape is not a power of 2, when qid_shape is not provided. 

Yep

>  On that note, there could be an error handling in place when the provide qid_shape and state vector is not compatible as well. Thoughts?

:+1:

**Comment by jeeva2812** [comment]
Sent out a pull request for handling this #6179
