### ISSUE TITLE
Docs in quantumai.google not up to date

### ISSUE THREAD

**Issue by fg-aqt** [quantumlib/Cirq#6587]
**Description of the issue**

The docs at https://quantumai.google/cirq/hardware/aqt are outdated and do not reflect the changes done in #6441. We assumed the docs would be updated automatically when the pull request was merged.

Are there additional steps required?

**How to reproduce the issue**

The content of
- https://quantumai.google/cirq/hardware/aqt/access and
- https://quantumai.google/cirq/hardware/aqt/getting_started

does not correspond to the version in main:

- https://github.com/quantumlib/Cirq/blob/main/docs/hardware/aqt/access.md
- https://github.com/quantumlib/Cirq/blob/main/docs/hardware/aqt/getting_started.ipynb

**Comment by fg-aqt** [comment]
@pavoljuhas can you provide some details regarding this issue? Is there something we from AQT can do?

**Comment by pavoljuhas** [comment]
@fg-aqt thank you for reporting this.  We have an internal staging version of the cirq website which is updated by a cron job every day, but this was failing for some time.  Hopefully, this is fixed by #6615.  I am waiting for the next cron run to confirm and close this issue.

Unfortunately, the staging website is not publicly available.  The public docs (and the aqt links) are updated after a stable cirq release which we expect to do within few weeks.

**Comment by pavoljuhas** [comment]
Internal doc builds are still failing, reported as b/342479711.

**Comment by pavoljuhas** [comment]
Doc build passes and the internal staging website is up to date.  Closing as fixed.

**Comment by pavoljuhas** [comment]
Reopening - the docs build and website update failed after stable release of Cirq-v1.4.0.
Reported as b/342479711.

**Comment by fg-aqt** [comment]
As the authentication is now up to date, this can be closed
