### ISSUE TITLE
Define numpy dtypes for protocols that apply to numpy objects

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#662]

**Comment by Strilanc** [comment]
We're using complex128 at the moment, and the tests fail if given complex64.

**Comment by dabacon** [comment]
Yes but this does not agree with the simulators

**Comment by dabacon** [comment]
If we standardize to some dtype then we should make sure that is documented.  If we don't standardize we should provide dtype as information to the protocol method so that implementors can use that type.  Alternatively we can make consumers of the protocol be required to convert dtypes.

Tradeoff is that type conversion might be costly.  If we pass in different dtypes then code gets more complex (though I think often it will just pass in dtypes to objects that are constructed).

**Comment by mpharrigan** [comment]
closing due to incomplete specification; please reopen with more detail if this is still a problem
