### ISSUE TITLE
Cannot serialize op cirq.CNOT

### ISSUE THREAD

**Issue by ikd-sci** [quantumlib/Cirq#6816]
**Description of the issue**

A simple circuit involving one CNOT gate can't be serialized to proto

**How to reproduce the issue**

```
cirq_google.serialization.CircuitSerializer().serialize(cirq.Circuit(cirq.CNOT.on(cirq.LineQubit(0), cirq.LineQubit(1))))
```

**Cirq version**
```
1.5.0.dev20241105230840
```

**Comment by maffoo** [comment]
This is intentional, because the `CircuitSerializer` creates protos meant to run on hardware via qcs, and hardware does not support CNOT natively. You have to translate the circuit to a gateset that is natively supported by hardware for it to run, and this limited gateset is all that is included in the proto schema. For serializing generic circuits and other cirq objects you can use the json format. Is there any reason why json serialization wouldn't work for your use case?

**Comment by mhucka** [comment]
Discussed during Cirq Cynq 2024-12-11: This was done by design, for the way the hardware works.

Will follow up with the OP about why he needs the serialization – what's the use case or situation.
