### ISSUE TITLE
Specify simple commutation relationships between gates

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#728]
For example this could be useful when inserting CZs, because it would allow later CZs to pass over earlier CZs and find a better spot in the circuit.

**Comment by bryano** [comment]
What about doing this dynamically for `KnownMatrixGate`s? Maybe use some sort of cache to avoid redoing the same check over and over. The only alternative I see is enumerating a set of gates that each gate is known to commute with, but that seems messy.

**Comment by dabacon** [comment]
We now have the `_commutes_` protocol for this, thought it has problems.

The fundamental problem is that objects that directly implement it need to know the set of other gates that it can act on.  Without the notion of "belong to these gates which form a group" this ends up being a rather bad blowup. 

Closing this issue since we have a protocol, but think we should think about how this should work for sets of gates that form a group (Pauli, Clifford) and not just generators of a group.
