### ISSUE TITLE
Improve and expand cirq's ability to simulate noise

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#730]
This issue is for discussing and tracking how we should improve cirq's noise capabilities.

My opinions follow.

---

Right now cirq's noise story is quite clunky. Our original idea was to keep the noise stuff out of the simulator by instead having code to take a circuit and return a noisy version (e.g. with extra parameterized Paulis that you could then sweep over). @dstrain115 implemented this for us, and the code is currently in contrib. However, on reflection (and a bit of user feedback, and realizing the simulator can be significantly simpified via `np.einsum`) I think it is clear this design is not the way to go.

The easily-fixed problem is that the noise code as-is is hard to use. The more serious problem is that conceptually the noise is really about the thing running the circuit as opposed to the circuit itself. It's somehow weird to say "okay now give me a noisy circuit" instead of "now do a noisy simulation of this circuit".

Refactoring the code to be in the simulator is one aspect of this issue. The other aspect is expanding the noise to include non-markovian noise models. @danielsank has offered to help with this, which should be useful because he has some experience with the problem and with the hardware. Quantum Benchmark has also offered to help; I don't know their github IDs but I will link them to this issue.

**Comment by Strilanc** [comment]
I actually don't know how much generality we want; I'm very much a beginner when it comes to noise. Do you have any opinions about it? What types of noise are useful, why are they useful, how hard are they to do (engineering-effort wise and cpu-effort wise), etc?

**Comment by jjwallman** [comment]
There are a few classes of non-Markovian noise, that have different difficulties associated with them.

Class 1: coupling to a common environment. This one is quite painful to implement because it requires a lot of matrix exponentials and a larger quantum system. It also makes time-ordering of gates extremely important, which is a feature from the realism side, but much harder on the software- and ease-of-use side.

Class 2: random channels drawn from a time- (and gate-) dependent ensemble of channels. This is relatively easy to implement and somewhat realistic. The big performance hit is that to accurately represent the physics, you have to simulate measurements at the single-shot level rather than computing the final probability distribution and sampling that repeatedly. This will typically add 100 times the simulation overhead. The other performance hit, which I think is relatively minor, is that you can no longer cache all the noise channels.

**Comment by Strilanc** [comment]
For class 2, I think you could get the final distribution (and then repeatedly sample from it) with a single simulation run. You would do so by performing a density matrix simulation instead of a wavefunction simulation.

On the other hand, the cost of the density matrix simulation is analogous to setting the number of wavefunction repetitions to 2^N where N is the number of qubits. But 2^N is usually more than the number of samples you'd want... maybe not so useful.

**Comment by jjwallman** [comment]
Actually, even with probabilistic unitary noise, class 2 cannot be easily simulated using a density matrix because the effective channel for the whole circuit does not factorize as a matrix product of individual channels per gate.

I was also assuming that you would subclass pure-state and density-matrix simulators from a common abstract class, as some channels of interest, e.g., amplitude damping, cannot be represented as a probabilistic mixture of unitary matrices.

**Comment by Strilanc** [comment]
I see. Do you happen to have a simple example of a channel that doesn't factorize in the way you mentioned? (A paper or textbook reference also works.)

**Comment by jjwallman** [comment]
I can't remember a good reference off the top of my head :)

Consider the following ideal experiment:

1. Prepare a state \phi
2. Apply a Z rotation by x1
3. Apply a Z rotation by x2
4. Measure \phi vs not \phi

Now suppose that x1~N(x,s) is normally distributed, representing a calibration error (supposing the experiment is re-calibrated every shot) and that x2~N(x1, d) is normally distributed with a mean dependent upon x1, representing a random drift.

Then for any individual run, Z_x2 Z_x1 (in operator order) factorizes, but the average does not because x2 depends upon x1.

**Comment by DanielSank** [comment]
Speaking as an experimentalist, a large set of useful cases is covered by class 2.

Class 1 is interesting and potentially useful, but I think a massive chunk of the utility is in Class 2.

**Comment by jjwallman** [comment]
I agree @DanielSank. It is convenient that Class 2 is also the easier one to simulate!

**Comment by DanielSank** [comment]
> Now suppose that x1~N(x,s) is normally distributed, representing a calibration error (supposing the experiment is re-calibrated every shot) and that x2~N(x1, d) is normally distributed with a mean dependent upon x1, representing a random drift.

I'm not sure what that comment is saying because of the strike through. Is the idea that x2 is a random variable whose distribution depends on x1?

**Comment by jjwallman** [comment]
Did you refresh? I forgot to escape the \~ but edited immediately after posting

**Comment by jjwallman** [comment]
and yes, that is the idea

**Comment by vtomole** [comment]
Closing because we have made a lot of progress in simulating noise. Even though there is still more work to do, this issue is not specific enough to define when to close.
