### ISSUE TITLE
Numpy version 1.15.0 causes some Xmon simulator tests to fail

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#746]

**Comment by Strilanc** [comment]
After some investigation, I have tracked this down to what appears to be a bug in the interaction between `multiprocessing` and `numpy`. The fault is that, in `cirq/google/sim/mem_manager.py`, the shape of an 2d array is lost when the first index has length 1.

The simplest way to repro the bug is to modify the body of `create_array` to check that what went in actually came out:

```python
        result = SharedMemManager._instance._create_array(arr)
        np.testing.assert_equal(SharedMemManager.get_array(result), arr)
        return result
```

and modify `_create_array` to print out what is stored:

```python
        print("STORING", arr)
        raw_arr = RawArray(c_arr._type_, c_arr)
```

and modify `_get_array` to print out what is retrieved:

```python
            result = np.ctypeslib.as_array(self._arrays[handle])
            print("RETRIEVED", result)
            return result
```

At which point you will get this output when running `pytest cirq/google/sim/xmon_stepper_test.py -v --maxfail=1`:

```
>       np.testing.assert_equal(SharedMemManager.get_array(result), arr)
E       AssertionError: 
E       Arrays are not equal
E       
E       (shapes (2,), (1, 2) mismatch)
E        x: array([0, 1])
E        y: array([[0, 1]])

cirq/google/sim/mem_manager.py:147: AssertionError
----------- Captured stdout call -----------
STORING [[0 1]]
RETRIEVED [0 1]
```

@dabacon Any idea why this would be happening?

**Comment by Strilanc** [comment]
I have reported this issue on the numpy repository: https://github.com/numpy/numpy/issues/11636

In the meantime, we'll work around the issue by manually tracking the shape: https://github.com/quantumlib/Cirq/pull/773
