### ISSUE TITLE
Add IndexedQubit class in the same vein as NamedQubit

### ISSUE THREAD

**Issue by ss2165** [quantumlib/Cirq#797]
Qubit represented by integer/index rather than name or co-ordinates.
Used in pytket, can merge in if useful generally?
Implemented at https://github.com/ss2165/Cirq/commit/cd83e620ca6519efdd8dd9cbffda32a1b54bd55e

**Comment by Strilanc** [comment]
Thanks for the suggestion. We actually already have this; we just call it `LineQubit` instead of `IndexedQubit`.

In the future, feel free to make a pull request from your forked repo's branch into this repository instead-of / in-addition-to opening an issue. Maintainers *love* it when you state your feature request in the form of a pull request.

Since we have a similar class, I will tentatively close this issue.

**Comment by ss2165** [comment]
I was aware of LineQubit but thought of it in the same local sense as GridQubit (i.e. the identifier corresponds to a location) and wanted something more abstract like NamedQubit. But they do the same job, so I'll switch my implementation to use LineQubit.
