### ISSUE TITLE
Implement cirq.H with EigenGate so cirq.H**0.5 works

### ISSUE THREAD

**Issue by babbush** [quantumlib/Cirq#872]
writing `cirq.H(ancilla_qubit) ** 0.5` gives the error:
"Expected a <class 'cirq.ops.gate_features.ExtrapolatableEffect'> but got cirq.H"

This is probably expected behavior but I don't understand it. Why isn't Hadamard extrapolatable?

**Comment by Strilanc** [comment]
It's just not implemented. I agree that it should be.

**Comment by vtomole** [comment]
How do you calculate `_eigen_components`? The docs give an example with Pauli-X, but i'm having a problem deriving them. From the docs: `The first component of a tuple is how much that eigenspace should be phased by applying the gate` How is that phase factor calculated?

**Comment by bryano** [comment]
The eigenvalues of a unitary are of the form λ=e<sup>iθ</sup>; the phase factor is θ/π.

The second component is the projector onto the subspace with eigenvalue λ.

**Comment by vtomole** [comment]
Alright. I still don't know where `[[0.5, 0.5], [0.5, 0.5]]` comes from. The eigenvalues of Pauli-X are `λ_1 = -1` and `λ_2 = 1` so for `-1 = e^iθ` , `θ = π`, so the phase factor would be `1`, for `1 = e^iθ`, `θ = 0`. Phase factor is 0. Where does `[[0.5, 0.5], [0.5, 0.5]]` fit in with this?

**Comment by bryano** [comment]
The ±1 eigenvalue corresponds to the eigenvector |±⟩ = [[1 / sqrt(2)], [±1 / sqrt(2)]]. The projector is then 
|±⟩⟨±| = [[1/2, ±1/2], [±1/2, 1/2]].

**Comment by vtomole** [comment]
@Strilanc I'm sorry. I don't understand. The H matrix has the same eigenvalues as the X matrix. I think i'm having problems understanding what an eigenspace is. X and H have different eigenspaces. What are they?

**Comment by Strilanc** [comment]
The eigenvectors of the Pauli X gate are |+⟩ = √½(|0⟩ + |1⟩) and |-⟩ = √½(|0⟩ - |1⟩). The eigenvalues of those vectors are -1 and +1 respectively. This means that X = |+⟩⟨+| + (-1)*|-⟩⟨-|. In prose, that equation basically reads "X takes |+⟩ to |+⟩ and |-⟩ to -|-⟩".

|+⟩⟨+| is [[1/2, 1/2], [1/2, 1/2]]. It is a matrix that sends |+⟩ to |+⟩ and everything else to 0. It is a projection matrix onto the +1 eigenspace of the X operation. |-⟩⟨-| is a projection matrix onto the -1 eigenspace of the X operation.

When you compute the square root of a matrix, what you are actually doing is square-rooting its eigenvalues. So, if M = x |a⟩⟨a| + y |b⟩⟨b| then √M = √x |a⟩⟨a| + √y |b⟩⟨b|. This applies to basically every other function you would care about. So, if I give you x, y, |a⟩⟨a|, and |b⟩⟨b|, it's very easy for you to compute functions of the matrix. And EigenGate asks for those values, almost. Instead of asking for x it asks for Imag(log(x)/pi) because it knows x is of the form exp(i pi theta) and it really wants theta.

According to wolfram alpha, these are the eigenvectors of the Hadamard matrix:

![image](https://user-images.githubusercontent.com/79941/45114608-4924ce80-b102-11e8-95f1-73cabae8ada5.png)
